org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# Set this before publishing, for example: githubRepository=your-name/vovremya
githubRepository=
