package com.vovremya.alarm.localization

import java.util.Locale

private data class Translation(
    val ru: String,
    val en: String,
    val de: String,
    val fr: String,
    val es: String,
    val uk: String,
)

private fun t(ru: String, en: String, de: String, fr: String, es: String, uk: String) =
    Translation(ru, en, de, fr, es, uk)

private val translations = listOf(
    t("Вовремя", "On Time", "Pünktlich", "À l’heure", "A tiempo", "Вчасно"),
    t("Событие", "Event", "Termin", "Événement", "Evento", "Подія"),
    t("Календарь", "Calendar", "Kalender", "Calendrier", "Calendario", "Календар"),
    t("Ближайшие", "Upcoming", "Demnächst", "À venir", "Próximas", "Найближчі"),
    t("Все подходящие события", "All matching events", "Alle passenden Termine", "Tous les événements correspondants", "Todos los eventos compatibles", "Усі відповідні події"),
    t("По одному событию на день", "One event per day", "Ein Termin pro Tag", "Un événement par jour", "Un evento al día", "Одна подія на день"),
    t("Обновить", "Refresh", "Aktualisieren", "Actualiser", "Actualizar", "Оновити"),
    t("Календарь проверяется каждый день в %s. Приложение не работает постоянно в фоне.", "The calendar is checked daily at %s. The app does not run constantly in the background.", "Der Kalender wird täglich um %s geprüft. Die App läuft nicht dauerhaft im Hintergrund.", "Le calendrier est vérifié chaque jour à %s. L’application ne fonctionne pas en permanence en arrière-plan.", "El calendario se revisa cada día a las %s. La aplicación no se ejecuta constantemente en segundo plano.", "Календар перевіряється щодня о %s. Застосунок не працює постійно у фоні."),
    t("Событие в %s · %s", "Event at %s · %s", "Termin um %s · %s", "Événement à %s · %s", "Evento a las %s · %s", "Подія о %s · %s"),
    t("Событие в %s", "Event at %s", "Termin um %s", "Événement à %s", "Evento a las %s", "Подія о %s"),
    t("%s · событие %s", "%s · event %s", "%s · Termin %s", "%s · événement %s", "%s · evento %s", "%s · подія %s"),
    t("Настройки", "Settings", "Einstellungen", "Réglages", "Ajustes", "Налаштування"),
    t("Назад", "Back", "Zurück", "Retour", "Atrás", "Назад"),
    t("Завершим настройку", "Finish setup", "Einrichtung abschließen", "Terminer la configuration", "Finalizar configuración", "Завершімо налаштування"),
    t("Android просит разрешения отдельно — данные календаря остаются только на телефоне.", "Android requests permissions separately — calendar data stays on your phone.", "Android fragt Berechtigungen einzeln ab – Kalenderdaten bleiben auf dem Telefon.", "Android demande chaque autorisation séparément — les données restent sur le téléphone.", "Android solicita los permisos por separado; los datos se quedan en el teléfono.", "Android запитує дозволи окремо — дані календаря залишаються на телефоні."),
    t("Доступ к календарю", "Calendar access", "Kalenderzugriff", "Accès au calendrier", "Acceso al calendario", "Доступ до календаря"),
    t("Уведомления", "Notifications", "Benachrichtigungen", "Notifications", "Notificaciones", "Сповіщення"),
    t("Точное время сигнала", "Exact alarm timing", "Genaue Weckzeit", "Heure exacte de l’alarme", "Hora exacta de alarma", "Точний час сигналу"),
    t("Экран будильника", "Alarm screen", "Weckerbildschirm", "Écran d’alarme", "Pantalla de alarma", "Екран будильника"),
    t("Готово", "Done", "Fertig", "Terminé", "Listo", "Готово"),
    t("Разрешить", "Allow", "Erlauben", "Autoriser", "Permitir", "Дозволити"),
    t("Всё спокойно", "All clear", "Alles ruhig", "Tout est calme", "Todo tranquilo", "Усе спокійно"),
    t("Следующий будильник появится после проверки календаря", "Your next alarm will appear after the calendar check", "Der nächste Wecker erscheint nach der Kalenderprüfung", "La prochaine alarme apparaîtra après la vérification", "La próxima alarma aparecerá tras revisar el calendario", "Наступний будильник з’явиться після перевірки календаря"),
    t("СЛЕДУЮЩИЙ БУДИЛЬНИК", "NEXT ALARM", "NÄCHSTER WECKER", "PROCHAINE ALARME", "PRÓXIMA ALARMA", "НАСТУПНИЙ БУДИЛЬНИК"),
    t("Подходящих событий нет", "No matching events", "Keine passenden Termine", "Aucun événement correspondant", "No hay eventos compatibles", "Немає відповідних подій"),
    t("Нужен доступ к календарю", "Calendar access required", "Kalenderzugriff erforderlich", "Accès au calendrier requis", "Se necesita acceso al calendario", "Потрібен доступ до календаря"),
    t("Разрешите доступ в карточке выше", "Allow access in the card above", "Zugriff oben erlauben", "Autorisez l’accès dans la carte ci-dessus", "Permite el acceso en la tarjeta superior", "Дозвольте доступ у картці вище"),
    t("Оформление", "Appearance", "Darstellung", "Apparence", "Apariencia", "Оформлення"),
    t("Цвет и режим интерфейса", "Interface color and mode", "Farbe und Darstellungsmodus", "Couleur et mode de l’interface", "Color y modo de la interfaz", "Колір і режим інтерфейсу"),
    t("Режим", "Mode", "Modus", "Mode", "Modo", "Режим"),
    t("Как на телефоне", "Follow phone", "Wie auf dem Telefon", "Comme le téléphone", "Como el teléfono", "Як на телефоні"),
    t("Светлый", "Light", "Hell", "Clair", "Claro", "Світлий"),
    t("Тёмный", "Dark", "Dunkel", "Sombre", "Oscuro", "Темний"),
    t("Основной цвет", "Accent color", "Akzentfarbe", "Couleur principale", "Color principal", "Основний колір"),
    t("Фиолетовый", "Violet", "Violett", "Violet", "Violeta", "Фіолетовий"),
    t("Синий", "Blue", "Blau", "Bleu", "Azul", "Синій"),
    t("Зелёный", "Green", "Grün", "Vert", "Verde", "Зелений"),
    t("Оранжевый", "Orange", "Orange", "Orange", "Naranja", "Помаранчевий"),
    t("Розовый", "Rose", "Rosa", "Rose", "Rosa", "Рожевий"),
    t("Бирюзовый", "Teal", "Türkis", "Turquoise", "Turquesa", "Бірюзовий"),
    t("Время", "Time", "Zeit", "Heure", "Hora", "Час"),
    t("Точная настройка планирования", "Precise scheduling settings", "Genaue Zeitplanung", "Réglages précis de planification", "Ajustes precisos de planificación", "Точні налаштування планування"),
    t("без опережения", "no lead time", "ohne Vorlauf", "sans avance", "sin antelación", "без випередження"),
    t("до начала", "before start", "vor Beginn", "avant le début", "antes del inicio", "до початку"),
    t("Задать дни, часы и минуты", "Set days, hours and minutes", "Tage, Stunden und Minuten festlegen", "Définir jours, heures et minutes", "Definir días, horas y minutos", "Задати дні, години та хвилини"),
    t("Ограничить поздние события", "Limit late events", "Späte Termine begrenzen", "Limiter les événements tardifs", "Limitar eventos tardíos", "Обмежити пізні події"),
    t("Ограничение выключено", "Limit is off", "Begrenzung ist aus", "Limite désactivée", "Límite desactivado", "Обмеження вимкнено"),
    t("Не позже %s", "No later than %s", "Nicht später als %s", "Au plus tard à %s", "No más tarde de las %s", "Не пізніше %s"),
    t("Последнее допустимое время", "Latest allowed time", "Späteste erlaubte Zeit", "Dernière heure autorisée", "Última hora permitida", "Останній допустимий час"),
    t("Проверять события вперёд", "Look ahead", "Vorschauzeitraum", "Période à vérifier", "Período de búsqueda", "Перевіряти події наперед"),
    t("Будильники", "Alarms", "Wecker", "Alarmes", "Alarmas", "Будильники"),
    t("События, звук и повтор сигнала", "Events, sound and snooze", "Termine, Ton und Schlummern", "Événements, son et répétition", "Eventos, sonido y repetición", "Події, звук і повтор сигналу"),
    t("Все события за день", "All events in a day", "Alle Termine eines Tages", "Tous les événements du jour", "Todos los eventos del día", "Усі події за день"),
    t("Будильник для каждого подходящего события", "Alarm for every matching event", "Wecker für jeden passenden Termin", "Alarme pour chaque événement correspondant", "Alarma para cada evento compatible", "Будильник для кожної відповідної події"),
    t("Только самое раннее событие дня", "Only the earliest event of the day", "Nur der früheste Termin des Tages", "Uniquement le premier événement du jour", "Solo el primer evento del día", "Лише найраніша подія дня"),
    t("События на весь день", "All-day events", "Ganztägige Termine", "Événements sur la journée", "Eventos de todo el día", "Події на весь день"),
    t("Использовать для них выбранное условное время", "Use the selected assumed time", "Die gewählte Ersatzzeit verwenden", "Utiliser l’heure indicative choisie", "Usar la hora estimada elegida", "Використовувати вибраний умовний час"),
    t("Условное время события", "Assumed event time", "Ersatzzeit des Termins", "Heure indicative", "Hora estimada del evento", "Умовний час події"),
    t("Звук", "Sound", "Ton", "Son", "Sonido", "Звук"),
    t("Проигрывать выбранную мелодию", "Play the selected sound", "Gewählten Ton abspielen", "Lire la sonnerie choisie", "Reproducir el sonido elegido", "Відтворювати вибрану мелодію"),
    t("Мелодия будильника", "Alarm sound", "Weckton", "Sonnerie de l’alarme", "Sonido de alarma", "Мелодія будильника"),
    t("Системная по умолчанию", "System default", "Systemstandard", "Sonnerie système", "Predeterminado del sistema", "Системна за замовчуванням"),
    t("Выбрана пользователем", "Custom sound", "Benutzerdefiniert", "Sonnerie personnalisée", "Sonido personalizado", "Вибрана користувачем"),
    t("Вибрация", "Vibration", "Vibration", "Vibration", "Vibración", "Вібрація"),
    t("Повторяющийся вибросигнал", "Repeating vibration", "Wiederholte Vibration", "Vibration répétée", "Vibración repetida", "Повторюваний вібросигнал"),
    t("Отложить сигнал", "Snooze", "Schlummern", "Reporter l’alarme", "Posponer alarma", "Відкласти сигнал"),
    t("Автоматически выключить звук", "Auto-silence", "Automatisch stummschalten", "Arrêt automatique du son", "Silenciar automáticamente", "Автоматично вимкнути звук"),
    t("Дни недели", "Days of week", "Wochentage", "Jours de la semaine", "Días de la semana", "Дні тижня"),
    t("В какие дни создавать будильник", "Days when alarms are created", "Tage für Wecker", "Jours de création des alarmes", "Días para crear alarmas", "У які дні створювати будильник"),
    t("Ни один день не выбран — будильники не создаются", "No day selected — no alarms will be created", "Kein Tag gewählt – es werden keine Wecker erstellt", "Aucun jour choisi — aucune alarme ne sera créée", "No hay días seleccionados: no se crearán alarmas", "Не вибрано жодного дня — будильники не створюються"),
    t("Календари", "Calendars", "Kalender", "Calendriers", "Calendarios", "Календарі"),
    t("Источники событий на этом телефоне", "Event sources on this phone", "Termin-Quellen auf diesem Telefon", "Sources d’événements sur ce téléphone", "Fuentes de eventos de este teléfono", "Джерела подій на цьому телефоні"),
    t("Разрешить доступ к календарю", "Allow calendar access", "Kalenderzugriff erlauben", "Autoriser l’accès au calendrier", "Permitir acceso al calendario", "Дозволити доступ до календаря"),
    t("На устройстве не найдено календарей", "No calendars found on this device", "Keine Kalender auf dem Gerät gefunden", "Aucun calendrier trouvé sur l’appareil", "No se encontraron calendarios en el dispositivo", "На пристрої не знайдено календарів"),
    t("Найдено общих календарей: %d", "Shared calendars found: %d", "Freigegebene Kalender gefunden: %d", "Calendriers partagés trouvés : %d", "Calendarios compartidos encontrados: %d", "Знайдено спільних календарів: %d"),
    t("У календарей без синхронизации Android может не хранить события. Включите их синхронизацию в Google Calendar; уже загруженные записи приложение проверит напрямую.", "Android may not store events from calendars with sync disabled. Enable sync in Google Calendar; the app checks already downloaded entries directly.", "Android speichert Termine aus Kalendern ohne Synchronisierung eventuell nicht. Aktivieren Sie die Synchronisierung in Google Kalender; bereits geladene Einträge werden direkt geprüft.", "Android peut ne pas stocker les événements des calendriers non synchronisés. Activez la synchronisation dans Google Agenda ; les entrées déjà téléchargées sont vérifiées directement.", "Android puede no guardar eventos de calendarios sin sincronización. Actívala en Google Calendar; la aplicación revisa directamente los eventos ya descargados.", "Android може не зберігати події календарів без синхронізації. Увімкніть її в Google Calendar; уже завантажені записи застосунок перевірить безпосередньо."),
    t("Скрытые календари тоже проверяются напрямую, но повторяющиеся события надёжнее читать после включения показа календаря.", "Hidden calendars are also checked directly, but recurring events are more reliable when the calendar is visible.", "Ausgeblendete Kalender werden ebenfalls direkt geprüft; Serientermine sind jedoch zuverlässiger, wenn der Kalender sichtbar ist.", "Les calendriers masqués sont aussi vérifiés directement, mais les événements récurrents sont plus fiables lorsque le calendrier est visible.", "Los calendarios ocultos también se revisan directamente, pero los eventos recurrentes son más fiables si el calendario está visible.", "Приховані календарі також перевіряються безпосередньо, але повторювані події надійніше читати, коли календар видимий."),
    t("Общий", "Shared", "Freigegeben", "Partagé", "Compartido", "Спільний"),
    t("синхронизация выключена", "sync is off", "Synchronisierung aus", "synchronisation désactivée", "sincronización desactivada", "синхронізацію вимкнено"),
    t("календарь скрыт", "calendar is hidden", "Kalender ausgeblendet", "calendrier masqué", "calendario oculto", "календар приховано"),
    t("владелец %s", "owner %s", "Eigentümer %s", "propriétaire %s", "propietario %s", "власник %s"),
    t("Все календари уже выбраны", "All calendars are selected", "Alle Kalender sind ausgewählt", "Tous les calendriers sont sélectionnés", "Todos los calendarios están seleccionados", "Усі календарі вже вибрані"),
    t("Выбрать все календари", "Select all calendars", "Alle Kalender auswählen", "Sélectionner tous les calendriers", "Seleccionar todos los calendarios", "Вибрати всі календарі"),
    t("Планирование", "Planning", "Planung", "Planification", "Planificación", "Планування"),
    t("Ежедневно в %s", "Daily at %s", "Täglich um %s", "Chaque jour à %s", "Cada día a las %s", "Щодня о %s"),
    t("Время проверки календарей", "Calendar check time", "Zeit der Kalenderprüfung", "Heure de vérification", "Hora de revisión", "Час перевірки календарів"),
    t("Точное планирование включено", "Exact scheduling enabled", "Genaue Planung aktiviert", "Planification exacte activée", "Planificación exacta activada", "Точне планування ввімкнено"),
    t("Разрешить точное время", "Allow exact timing", "Genaue Zeit erlauben", "Autoriser l’heure exacte", "Permitir hora exacta", "Дозволити точний час"),
    t("Ещё не проверялось", "Not checked yet", "Noch nicht geprüft", "Pas encore vérifié", "Aún no se ha revisado", "Ще не перевірялося"),
    t("Последняя проверка %s", "Last checked %s", "Zuletzt geprüft %s", "Dernière vérification %s", "Última revisión %s", "Остання перевірка %s"),
    t("Ошибки и журнал", "Errors and log", "Fehler und Protokoll", "Erreurs et journal", "Errores y registro", "Помилки та журнал"),
    t("Нажмите, чтобы скрыть", "Tap to hide", "Zum Ausblenden tippen", "Touchez pour masquer", "Toca para ocultar", "Натисніть, щоб приховати"),
    t("Скрыто · нажмите, чтобы раскрыть", "Hidden · tap to expand", "Ausgeblendet · zum Öffnen tippen", "Masqué · touchez pour ouvrir", "Oculto · toca para abrir", "Приховано · натисніть, щоб розкрити"),
    t("Проверить сейчас", "Check now", "Jetzt prüfen", "Vérifier maintenant", "Revisar ahora", "Перевірити зараз"),
    t("Обновления", "Updates", "Updates", "Mises à jour", "Actualizaciones", "Оновлення"),
    t("Через GitHub Releases", "Through GitHub Releases", "Über GitHub Releases", "Via GitHub Releases", "Mediante GitHub Releases", "Через GitHub Releases"),
    t("Проверять автоматически", "Check automatically", "Automatisch prüfen", "Vérifier automatiquement", "Comprobar automáticamente", "Перевіряти автоматично"),
    t("APK загрузится сам; установку подтверждает Android", "The APK downloads automatically; Android asks before installation", "Die APK wird automatisch geladen; Android bestätigt die Installation", "L’APK se télécharge automatiquement ; Android confirme l’installation", "El APK se descarga solo; Android confirma la instalación", "APK завантажиться автоматично; установлення підтверджує Android"),
    t("Проверить обновления", "Check for updates", "Nach Updates suchen", "Rechercher les mises à jour", "Buscar actualizaciones", "Перевірити оновлення"),
    t("Репозиторий не настроен", "Repository not configured", "Repository nicht eingerichtet", "Dépôt non configuré", "Repositorio no configurado", "Репозиторій не налаштовано"),
    t("Экономно для батареи", "Battery efficient", "Akkuschonend", "Économe en batterie", "Ahorra batería", "Економно для батареї"),
    t("Одна плановая проверка в сутки и только нужные системные сигналы — без постоянного сервиса.", "One scheduled check per day and only required system alarms — no permanent service.", "Eine geplante Prüfung pro Tag und nur nötige Systemwecker – kein dauerhafter Dienst.", "Une vérification par jour et uniquement les alarmes système nécessaires — aucun service permanent.", "Una revisión programada al día y solo las alarmas necesarias, sin servicio permanente.", "Одна планова перевірка на добу й лише потрібні системні сигнали — без постійної служби."),
    t("Опережение будильника", "Alarm lead time", "Vorlaufzeit des Weckers", "Avance de l’alarme", "Antelación de la alarma", "Випередження будильника"),
    t("Можно выбрать от момента начала до 14 суток заранее.", "Choose from the start time up to 14 days before.", "Von der Startzeit bis zu 14 Tage vorher wählbar.", "Choisissez entre l’heure de début et 14 jours avant.", "Elige desde la hora de inicio hasta 14 días antes.", "Можна вибрати від моменту початку до 14 діб заздалегідь."),
    t("Дни", "Days", "Tage", "Jours", "Días", "Дні"),
    t("Часы", "Hours", "Stunden", "Heures", "Horas", "Години"),
    t("Мин", "Min", "Min", "Min", "Min", "Хв"),
    t("Сохранить", "Save", "Speichern", "Enregistrer", "Guardar", "Зберегти"),
    t("Отмена", "Cancel", "Abbrechen", "Annuler", "Cancelar", "Скасувати"),
    t("В момент начала", "At start time", "Zum Startzeitpunkt", "À l’heure de début", "A la hora de inicio", "У момент початку"),
    t("%d дн", "%d d", "%d T", "%d j", "%d d", "%d дн"),
    t("%d ч", "%d h", "%d Std", "%d h", "%d h", "%d год"),
    t("%d мин", "%d min", "%d Min", "%d min", "%d min", "%d хв"),
    t("Итого: %s", "Total: %s", "Gesamt: %s", "Total : %s", "Total: %s", "Разом: %s"),
    t("Версия %s", "Version %s", "Version %s", "Version %s", "Versión %s", "Версія %s"),
    t("Сегодня", "Today", "Heute", "Aujourd’hui", "Hoy", "Сьогодні"),
    t("Завтра", "Tomorrow", "Morgen", "Demain", "Mañana", "Завтра"),
    t("скоро", "soon", "bald", "bientôt", "pronto", "скоро"),
    t("через %d дн.", "in %d d", "in %d T", "dans %d j", "en %d d", "через %d дн."),
    t("через %d ч", "in %d h", "in %d Std", "dans %d h", "en %d h", "через %d год"),
    t("Пора собираться", "Time to get ready", "Zeit, sich fertig zu machen", "Il est temps de se préparer", "Hora de prepararse", "Час збиратися"),
    t("ПОРА СОБИРАТЬСЯ", "TIME TO GET READY", "ZEIT, SICH FERTIG ZU MACHEN", "IL EST TEMPS DE SE PRÉPARER", "HORA DE PREPARARSE", "ЧАС ЗБИРАТИСЯ"),
    t("Весь день", "All day", "Ganztägig", "Toute la journée", "Todo el día", "Увесь день"),
    t("Я встал", "I’m up", "Ich bin wach", "Je suis debout", "Ya estoy despierto", "Я встав"),
    t("Отложить на %d мин", "Snooze for %d min", "%d Min schlummern", "Reporter de %d min", "Posponer %d min", "Відкласти на %d хв"),
    t("Подготавливаем обновление…", "Preparing update…", "Update wird vorbereitet…", "Préparation de la mise à jour…", "Preparando actualización…", "Готуємо оновлення…"),
    t("Будильник готов", "Alarm ready", "Wecker bereit", "Alarme prête", "Alarma lista", "Будильник готовий"),
    t("На ближайшие дни будильников нет", "No alarms for the coming days", "Keine Wecker für die nächsten Tage", "Aucune alarme pour les prochains jours", "No hay alarmas para los próximos días", "На найближчі дні будильників немає"),
    t("Сигнал перед событием", "Alarm before an event", "Wecker vor einem Termin", "Alarme avant un événement", "Alarma antes de un evento", "Сигнал перед подією"),
    t("Итог ежедневной проверки календаря", "Daily calendar check summary", "Ergebnis der täglichen Kalenderprüfung", "Résumé de la vérification quotidienne", "Resumen de la revisión diaria", "Підсумок щоденної перевірки календаря"),
    t("Новые версии из GitHub Releases", "New versions from GitHub Releases", "Neue Versionen aus GitHub Releases", "Nouvelles versions de GitHub Releases", "Nuevas versiones de GitHub Releases", "Нові версії з GitHub Releases"),
    t("звук и вибрация", "sound and vibration", "Ton und Vibration", "son et vibration", "sonido y vibración", "звук і вібрація"),
    t("только звук", "sound only", "nur Ton", "son uniquement", "solo sonido", "лише звук"),
    t("только вибрация", "vibration only", "nur Vibration", "vibration uniquement", "solo vibración", "лише вібрація"),
    t("без звука", "silent", "lautlos", "silencieux", "silencioso", "без звуку"),
    t("События не прочитаны: проверьте синхронизацию календарей", "Events could not be read: check calendar sync", "Termine konnten nicht gelesen werden: Kalendersynchronisierung prüfen", "Événements non lus : vérifiez la synchronisation", "No se pudieron leer los eventos: revisa la sincronización", "Події не прочитано: перевірте синхронізацію календарів"),
    t("Календарь не вернул событий на ближайшие %d дней", "The calendar returned no events for the next %d days", "Der Kalender lieferte für die nächsten %d Tage keine Termine", "Le calendrier n’a renvoyé aucun événement pour les %d prochains jours", "El calendario no devolvió eventos para los próximos %d días", "Календар не повернув подій на найближчі %d днів"),
    t("Календарь проверен — события не прошли выбранные фильтры", "Calendar checked — events did not match the selected filters", "Kalender geprüft – Termine entsprachen nicht den gewählten Filtern", "Calendrier vérifié — les événements ne correspondent pas aux filtres", "Calendario revisado: los eventos no coinciden con los filtros", "Календар перевірено — події не пройшли вибрані фільтри"),
    t("%s %s готово", "%s %s is ready", "%s %s ist bereit", "%s %s est prête", "%s %s está lista", "%s %s готово"),
    t("Нажмите, чтобы подтвердить установку обновления", "Tap to confirm update installation", "Tippen, um die Installation zu bestätigen", "Touchez pour confirmer l’installation", "Toca para confirmar la instalación", "Натисніть, щоб підтвердити встановлення оновлення"),
    t("Установлена последняя версия", "Latest version is installed", "Die neueste Version ist installiert", "La dernière version est installée", "Está instalada la última versión", "Установлено останню версію"),
    t("В последнем релизе нет APK", "The latest release has no APK", "Das neueste Release enthält keine APK", "La dernière version ne contient pas d’APK", "La última versión no contiene APK", "В останньому релізі немає APK"),
    t("Не удалось прочитать календарь", "Could not read the calendar", "Kalender konnte nicht gelesen werden", "Impossible de lire le calendrier", "No se pudo leer el calendario", "Не вдалося прочитати календар"),
    t("Оставьте хотя бы один календарь", "Keep at least one calendar selected", "Mindestens einen Kalender auswählen", "Gardez au moins un calendrier sélectionné", "Selecciona al menos un calendario", "Залиште вибраним хоча б один календар"),
    t("Версия %s загружена", "Version %s downloaded", "Version %s heruntergeladen", "Version %s téléchargée", "Versión %s descargada", "Версію %s завантажено"),
    t("Обновление: %s", "Update: %s", "Update: %s", "Mise à jour : %s", "Actualización: %s", "Оновлення: %s"),
    t("Календарь прочитан с ошибками — откройте скрытый журнал", "Calendar read with errors — open the hidden log", "Kalender mit Fehlern gelesen – verborgenes Protokoll öffnen", "Calendrier lu avec des erreurs — ouvrez le journal masqué", "Calendario leído con errores: abre el registro oculto", "Календар прочитано з помилками — відкрийте прихований журнал"),
    t("Найдено событий: %d; будильников: %d", "Events found: %d; alarms: %d", "Termine gefunden: %d; Wecker: %d", "Événements trouvés : %d ; alarmes : %d", "Eventos encontrados: %d; alarmas: %d", "Знайдено подій: %d; будильників: %d"),
    t("Будильников: %d; разрешите точное время", "Alarms: %d; allow exact timing", "Wecker: %d; genaue Zeit erlauben", "Alarmes : %d ; autorisez l’heure exacte", "Alarmas: %d; permite la hora exacta", "Будильників: %d; дозвольте точний час"),
    t("Событий не найдено. У %d календарей выключена синхронизация", "No events found. Sync is off for %d calendars", "Keine Termine gefunden. Synchronisierung ist bei %d Kalendern aus", "Aucun événement trouvé. La synchronisation est désactivée pour %d calendriers", "No se encontraron eventos. %d calendarios no están sincronizados", "Подій не знайдено. У %d календарів вимкнено синхронізацію"),
    t("В ближайшие %d дней календарь не вернул событий", "The calendar returned no events for the next %d days", "Der Kalender lieferte für die nächsten %d Tage keine Termine", "Le calendrier n’a renvoyé aucun événement pour les %d prochains jours", "El calendario no devolvió eventos para los próximos %d días", "Календар не повернув подій на найближчі %d днів"),
    t("Найдены только события на весь день — для них будильник не ставится", "Only all-day events found — no alarms are set for them", "Nur ganztägige Termine gefunden – dafür werden keine Wecker erstellt", "Seuls des événements sur la journée ont été trouvés — aucune alarme n’est créée", "Solo se encontraron eventos de todo el día; no se crean alarmas", "Знайдено лише події на весь день — для них будильник не встановлюється"),
    t("События найдены, но их календари отключены в настройках", "Events found, but their calendars are disabled in settings", "Termine gefunden, aber ihre Kalender sind in den Einstellungen deaktiviert", "Événements trouvés, mais leurs calendriers sont désactivés", "Se encontraron eventos, pero sus calendarios están desactivados", "Події знайдено, але їхні календарі вимкнено в налаштуваннях"),
    t("События найдены, но эти дни недели отключены", "Events found, but those weekdays are disabled", "Termine gefunden, aber diese Wochentage sind deaktiviert", "Événements trouvés, mais ces jours sont désactivés", "Se encontraron eventos, pero esos días están desactivados", "Події знайдено, але ці дні тижня вимкнено"),
    t("События найдены, но начинаются позже заданной метки", "Events found, but they start after the cutoff", "Termine gefunden, beginnen aber nach der Zeitgrenze", "Événements trouvés, mais ils commencent après la limite", "Se encontraron eventos, pero empiezan después del límite", "Події знайдено, але вони починаються пізніше заданої межі"),
    t("События найдены, но время будильника для них уже прошло", "Events found, but their alarm time has passed", "Termine gefunden, aber ihre Weckzeit ist bereits vorbei", "Événements trouvés, mais l’heure de leur alarme est passée", "Se encontraron eventos, pero su hora de alarma ya pasó", "Події знайдено, але час будильника для них уже минув"),
    t("Подходящих событий пока нет", "No matching events yet", "Noch keine passenden Termine", "Aucun événement correspondant pour le moment", "Aún no hay eventos compatibles", "Відповідних подій поки немає"),
    t("Нажмите обновить, чтобы проверить события", "Tap refresh to check events", "Zum Prüfen der Termine auf Aktualisieren tippen", "Touchez Actualiser pour vérifier les événements", "Toca actualizar para revisar los eventos", "Натисніть оновити, щоб перевірити події"),
    t("Android не вернул событий. Проверьте календари с выключенной синхронизацией в настройках", "Android returned no events. Check calendars with sync disabled in settings", "Android lieferte keine Termine. Prüfen Sie Kalender ohne Synchronisierung", "Android n’a renvoyé aucun événement. Vérifiez les calendriers non synchronisés", "Android no devolvió eventos. Revisa los calendarios sin sincronización", "Android не повернув подій. Перевірте календарі з вимкненою синхронізацією"),
    t("Android не вернул событий. Проверьте скрытые календари в настройках", "Android returned no events. Check hidden calendars in settings", "Android lieferte keine Termine. Prüfen Sie ausgeblendete Kalender", "Android n’a renvoyé aucun événement. Vérifiez les calendriers masqués", "Android no devolvió eventos. Revisa los calendarios ocultos", "Android не повернув подій. Перевірте приховані календарі"),
    t("Android не вернул событий на ближайшие %d дней", "Android returned no events for the next %d days", "Android lieferte für die nächsten %d Tage keine Termine", "Android n’a renvoyé aucun événement pour les %d prochains jours", "Android no devolvió eventos para los próximos %d días", "Android не повернув подій на найближчі %d днів"),
    t("Найдены только события на весь день", "Only all-day events found", "Nur ganztägige Termine gefunden", "Seuls des événements sur la journée ont été trouvés", "Solo se encontraron eventos de todo el día", "Знайдено лише події на весь день"),
    t("События есть, но их календари отключены в настройках", "Events exist, but their calendars are disabled in settings", "Termine vorhanden, aber ihre Kalender sind deaktiviert", "Des événements existent, mais leurs calendriers sont désactivés", "Hay eventos, pero sus calendarios están desactivados", "Події є, але їхні календарі вимкнено"),
    t("События есть, но нужные дни недели отключены", "Events exist, but the required weekdays are disabled", "Termine vorhanden, aber die benötigten Wochentage sind deaktiviert", "Des événements existent, mais les jours requis sont désactivés", "Hay eventos, pero los días necesarios están desactivados", "Події є, але потрібні дні тижня вимкнено"),
    t("События начинаются позже заданной метки", "Events start after the cutoff", "Termine beginnen nach der Zeitgrenze", "Les événements commencent après la limite", "Los eventos empiezan después del límite", "Події починаються пізніше заданої межі"),
    t("Время этих будильников уже прошло", "These alarm times have already passed", "Diese Weckzeiten sind bereits vorbei", "L’heure de ces alarmes est déjà passée", "La hora de estas alarmas ya pasó", "Час цих будильників уже минув"),
    t("Проверьте фильтры календарей, дней и времени в настройках", "Check calendar, weekday and time filters in settings", "Kalender-, Wochentag- und Zeitfilter prüfen", "Vérifiez les filtres de calendrier, de jour et d’heure", "Revisa los filtros de calendario, días y hora", "Перевірте фільтри календарів, днів і часу"),
    t("Будильник создан", "Alarm created", "Wecker erstellt", "Alarme créée", "Alarma creada", "Будильник створено"),
    t("Пропущено: событие на весь день", "Skipped: all-day event", "Übersprungen: ganztägiger Termin", "Ignoré : événement sur la journée", "Omitido: evento de todo el día", "Пропущено: подія на весь день"),
    t("Пропущено: событие отменено", "Skipped: canceled event", "Übersprungen: abgesagter Termin", "Ignoré : événement annulé", "Omitido: evento cancelado", "Пропущено: подію скасовано"),
    t("Пропущено: приглашение отклонено", "Skipped: invitation declined", "Übersprungen: Einladung abgelehnt", "Ignoré : invitation refusée", "Omitido: invitación rechazada", "Пропущено: запрошення відхилено"),
    t("Пропущено: календарь отключён в настройках", "Skipped: calendar disabled in settings", "Übersprungen: Kalender deaktiviert", "Ignoré : calendrier désactivé", "Omitido: calendario desactivado", "Пропущено: календар вимкнено"),
    t("Пропущено: день недели отключён", "Skipped: weekday disabled", "Übersprungen: Wochentag deaktiviert", "Ignoré : jour désactivé", "Omitido: día desactivado", "Пропущено: день тижня вимкнено"),
    t("Пропущено: позже временной метки", "Skipped: after cutoff", "Übersprungen: nach Zeitgrenze", "Ignoré : après la limite", "Omitido: después del límite", "Пропущено: пізніше часової межі"),
    t("Пропущено: время будильника уже прошло", "Skipped: alarm time passed", "Übersprungen: Weckzeit vorbei", "Ignoré : heure d’alarme passée", "Omitido: hora de alarma pasada", "Пропущено: час будильника минув"),
    t("Пропущено: на этот день уже выбран более ранний будильник", "Skipped: an earlier alarm is already selected for this day", "Übersprungen: früherer Wecker für diesen Tag gewählt", "Ignoré : une alarme plus tôt est déjà choisie", "Omitido: ya hay una alarma anterior para este día", "Пропущено: на цей день уже вибрано раніший будильник"),
    t("найдено резервным запросом", "found by fallback query", "durch Ersatzabfrage gefunden", "trouvé par requête de secours", "encontrado mediante consulta alternativa", "знайдено резервним запитом"),
).associateBy(Translation::ru)

fun appLocale(): Locale {
    val language = Locale.getDefault().language.lowercase(Locale.ROOT)
    val tag = if (language in setOf("ru", "en", "de", "fr", "es", "uk")) language else "en"
    return Locale.forLanguageTag(tag)
}

fun tr(source: String, vararg args: Any?): String {
    val translation = translations[source]
    val value = when (appLocale().language) {
        "ru" -> translation?.ru
        "de" -> translation?.de
        "fr" -> translation?.fr
        "es" -> translation?.es
        "uk" -> translation?.uk
        else -> translation?.en
    } ?: source
    return if (args.isEmpty()) value else String.format(appLocale(), value, *args)
}
