package com.vovremya.alarm.localization

import java.util.Locale

private data class Translation(
    val ru: String,
    val en: String,
    val de: String,
    val fr: String,
    val es: String,
    val uk: String,
)

private fun t(ru: String, en: String, de: String, fr: String, es: String, uk: String) =
    Translation(ru, en, de, fr, es, uk)

private val translations = listOf(
    t("Вовремя", "On Time", "Pünktlich", "À l’heure", "A tiempo", "Вчасно"),
    t("Событие", "Event", "Termin", "Événement", "Evento", "Подія"),
    t("Календарь", "Calendar", "Kalender", "Calendrier", "Calendario", "Календар"),
    t("Ближайшие", "Upcoming", "Demnächst", "À venir", "Próximas", "Найближчі"),
    t("Все подходящие события", "All matching events", "Alle passenden Termine", "Tous les événements correspondants", "Todos los eventos compatibles", "Усі відповідні події"),
    t("По одному событию на день", "One event per day", "Ein Termin pro Tag", "Un événement par jour", "Un evento al día", "Одна подія на день"),
    t("Обновить", "Refresh", "Aktualisieren", "Actualiser", "Actualizar", "Оновити"),
    t("Календарь проверяется каждый день в %s. Приложение не работает постоянно в фоне.", "The calendar is checked daily at %s. The app does not run constantly in the background.", "Der Kalender wird täglich um %s geprüft. Die App läuft nicht dauerhaft im Hintergrund.", "Le calendrier est vérifié chaque jour à %s. L’application ne fonctionne pas en permanence en arrière-plan.", "El calendario se revisa cada día a las %s. La aplicación no se ejecuta constantemente en segundo plano.", "Календар перевіряється щодня о %s. Застосунок не працює постійно у фоні."),
    t("Событие в %s · %s", "Event at %s · %s", "Termin um %s · %s", "Événement à %s · %s", "Evento a las %s · %s", "Подія о %s · %s"),
    t("Событие в %s", "Event at %s", "Termin um %s", "Événement à %s", "Evento a las %s", "Подія о %s"),
    t("%s · событие %s", "%s · event %s", "%s · Termin %s", "%s · événement %s", "%s · evento %s", "%s · подія %s"),
    t("Настройки", "Settings", "Einstellungen", "Réglages", "Ajustes", "Налаштування"),
    t("Назад", "Back", "Zurück", "Retour", "Atrás", "Назад"),
    t("Завершим настройку", "Finish setup", "Einrichtung abschließen", "Terminer la configuration", "Finalizar configuración", "Завершімо налаштування"),
    t("Android просит разрешения отдельно — данные календаря остаются только на телефоне.", "Android requests permissions separately — calendar data stays on your phone.", "Android fragt Berechtigungen einzeln ab – Kalenderdaten bleiben auf dem Telefon.", "Android demande chaque autorisation séparément — les données restent sur le téléphone.", "Android solicita los permisos por separado; los datos se quedan en el teléfono.", "Android запитує дозволи окремо — дані календаря залишаються на телефоні."),
    t("Доступ к календарю", "Calendar access", "Kalenderzugriff", "Accès au calendrier", "Acceso al calendario", "Доступ до календаря"),
    t("Доступ и синхронизация календаря", "Calendar access and sync", "Kalenderzugriff und Synchronisierung", "Accès et synchronisation du calendrier", "Acceso y sincronización del calendario", "Доступ і синхронізація календаря"),
    t("Уведомления", "Notifications", "Benachrichtigungen", "Notifications", "Notificaciones", "Сповіщення"),
    t("Точное время сигнала", "Exact alarm timing", "Genaue Weckzeit", "Heure exacte de l’alarme", "Hora exacta de alarma", "Точний час сигналу"),
    t("Экран будильника", "Alarm screen", "Weckerbildschirm", "Écran d’alarme", "Pantalla de alarma", "Екран будильника"),
    t("Готово", "Done", "Fertig", "Terminé", "Listo", "Готово"),
    t("Разрешить", "Allow", "Erlauben", "Autoriser", "Permitir", "Дозволити"),
    t("Всё спокойно", "All clear", "Alles ruhig", "Tout est calme", "Todo tranquilo", "Усе спокійно"),
    t("Следующий будильник появится после проверки календаря", "Your next alarm will appear after the calendar check", "Der nächste Wecker erscheint nach der Kalenderprüfung", "La prochaine alarme apparaîtra après la vérification", "La próxima alarma aparecerá tras revisar el calendario", "Наступний будильник з’явиться після перевірки календаря"),
    t("СЛЕДУЮЩИЙ БУДИЛЬНИК", "NEXT ALARM", "NÄCHSTER WECKER", "PROCHAINE ALARME", "PRÓXIMA ALARMA", "НАСТУПНИЙ БУДИЛЬНИК"),
    t("Подходящих событий нет", "No matching events", "Keine passenden Termine", "Aucun événement correspondant", "No hay eventos compatibles", "Немає відповідних подій"),
    t("Нужен доступ к календарю", "Calendar access required", "Kalenderzugriff erforderlich", "Accès au calendrier requis", "Se necesita acceso al calendario", "Потрібен доступ до календаря"),
    t("Разрешите доступ в карточке выше", "Allow access in the card above", "Zugriff oben erlauben", "Autorisez l’accès dans la carte ci-dessus", "Permite el acceso en la tarjeta superior", "Дозвольте доступ у картці вище"),
    t("Оформление", "Appearance", "Darstellung", "Apparence", "Apariencia", "Оформлення"),
    t("Цвет и режим интерфейса", "Interface color and mode", "Farbe und Darstellungsmodus", "Couleur et mode de l’interface", "Color y modo de la interfaz", "Колір і режим інтерфейсу"),
    t("Режим", "Mode", "Modus", "Mode", "Modo", "Режим"),
    t("Как на телефоне", "Follow phone", "Wie auf dem Telefon", "Comme le téléphone", "Como el teléfono", "Як на телефоні"),
    t("Светлый", "Light", "Hell", "Clair", "Claro", "Світлий"),
    t("Тёмный", "Dark", "Dunkel", "Sombre", "Oscuro", "Темний"),
    t("Основной цвет", "Accent color", "Akzentfarbe", "Couleur principale", "Color principal", "Основний колір"),
    t("Фиолетовый", "Violet", "Violett", "Violet", "Violeta", "Фіолетовий"),
    t("Синий", "Blue", "Blau", "Bleu", "Azul", "Синій"),
    t("Зелёный", "Green", "Grün", "Vert", "Verde", "Зелений"),
    t("Оранжевый", "Orange", "Orange", "Orange", "Naranja", "Помаранчевий"),
    t("Розовый", "Rose", "Rosa", "Rose", "Rosa", "Рожевий"),
    t("Бирюзовый", "Teal", "Türkis", "Turquoise", "Turquesa", "Бірюзовий"),
    t("Красный", "Red", "Rot", "Rouge", "Rojo", "Червоний"),
    t("Янтарный", "Amber", "Bernstein", "Ambre", "Ámbar", "Бурштиновий"),
    t("Лаймовый", "Lime", "Limette", "Citron vert", "Lima", "Лаймовий"),
    t("Голубой", "Cyan", "Cyan", "Cyan", "Cian", "Блакитний"),
    t("Индиго", "Indigo", "Indigo", "Indigo", "Índigo", "Індиго"),
    t("Графитовый", "Graphite", "Graphit", "Graphite", "Grafito", "Графітовий"),
    t("Свой цвет", "Custom color", "Eigene Farbe", "Couleur personnalisée", "Color personalizado", "Свій колір"),
    t("Фон", "Background", "Hintergrund", "Arrière-plan", "Fondo", "Фон"),
    t("Обычный", "Standard", "Standard", "Standard", "Estándar", "Звичайний"),
    t("С оттенком", "Tinted", "Getönt", "Teinté", "Tintado", "З відтінком"),
    t("Чёрный OLED", "OLED black", "OLED-Schwarz", "Noir OLED", "Negro OLED", "Чорний OLED"),
    t("Собственный цвет", "Custom color", "Eigene Farbe", "Couleur personnalisée", "Color personalizado", "Власний колір"),
    t("Введите HEX-код цвета", "Enter a HEX color code", "HEX-Farbcode eingeben", "Saisissez un code couleur HEX", "Introduce un código de color HEX", "Введіть HEX-код кольору"),
    t("Например: #6558D3", "Example: #6558D3", "Beispiel: #6558D3", "Exemple : #6558D3", "Ejemplo: #6558D3", "Наприклад: #6558D3"),
    t("Применить", "Apply", "Anwenden", "Appliquer", "Aplicar", "Застосувати"),
    t("Время", "Time", "Zeit", "Heure", "Hora", "Час"),
    t("Точная настройка планирования", "Precise scheduling settings", "Genaue Zeitplanung", "Réglages précis de planification", "Ajustes precisos de planificación", "Точні налаштування планування"),
    t("без опережения", "no lead time", "ohne Vorlauf", "sans avance", "sin antelación", "без випередження"),
    t("до начала", "before start", "vor Beginn", "avant le début", "antes del inicio", "до початку"),
    t("Задать дни, часы и минуты", "Set days, hours and minutes", "Tage, Stunden und Minuten festlegen", "Définir jours, heures et minutes", "Definir días, horas y minutos", "Задати дні, години та хвилини"),
    t("Ограничить поздние события", "Limit late events", "Späte Termine begrenzen", "Limiter les événements tardifs", "Limitar eventos tardíos", "Обмежити пізні події"),
    t("Ограничение выключено", "Limit is off", "Begrenzung ist aus", "Limite désactivée", "Límite desactivado", "Обмеження вимкнено"),
    t("Не позже %s", "No later than %s", "Nicht später als %s", "Au plus tard à %s", "No más tarde de las %s", "Не пізніше %s"),
    t("Последнее допустимое время", "Latest allowed time", "Späteste erlaubte Zeit", "Dernière heure autorisée", "Última hora permitida", "Останній допустимий час"),
    t("Проверять события вперёд", "Look ahead", "Vorschauzeitraum", "Période à vérifier", "Período de búsqueda", "Перевіряти події наперед"),
    t("Будильники", "Alarms", "Wecker", "Alarmes", "Alarmas", "Будильники"),
    t("События, звук и повтор сигнала", "Events, sound and snooze", "Termine, Ton und Schlummern", "Événements, son et répétition", "Eventos, sonido y repetición", "Події, звук і повтор сигналу"),
    t("Все события за день", "All events in a day", "Alle Termine eines Tages", "Tous les événements du jour", "Todos los eventos del día", "Усі події за день"),
    t("Будильник для каждого подходящего события", "Alarm for every matching event", "Wecker für jeden passenden Termin", "Alarme pour chaque événement correspondant", "Alarma para cada evento compatible", "Будильник для кожної відповідної події"),
    t("Только самое раннее событие дня", "Only the earliest event of the day", "Nur der früheste Termin des Tages", "Uniquement le premier événement du jour", "Solo el primer evento del día", "Лише найраніша подія дня"),
    t("События на весь день", "All-day events", "Ganztägige Termine", "Événements sur la journée", "Eventos de todo el día", "Події на весь день"),
    t("Использовать для них выбранное условное время", "Use the selected assumed time", "Die gewählte Ersatzzeit verwenden", "Utiliser l’heure indicative choisie", "Usar la hora estimada elegida", "Використовувати вибраний умовний час"),
    t("Условное время события", "Assumed event time", "Ersatzzeit des Termins", "Heure indicative", "Hora estimada del evento", "Умовний час події"),
    t("Звук", "Sound", "Ton", "Son", "Sonido", "Звук"),
    t("Проигрывать выбранную мелодию", "Play the selected sound", "Gewählten Ton abspielen", "Lire la sonnerie choisie", "Reproducir el sonido elegido", "Відтворювати вибрану мелодію"),
    t("Мелодия будильника", "Alarm sound", "Weckton", "Sonnerie de l’alarme", "Sonido de alarma", "Мелодія будильника"),
    t("Системная по умолчанию", "System default", "Systemstandard", "Sonnerie système", "Predeterminado del sistema", "Системна за замовчуванням"),
    t("Выбрана пользователем", "Custom sound", "Benutzerdefiniert", "Sonnerie personnalisée", "Sonido personalizado", "Вибрана користувачем"),
    t("Вибрация", "Vibration", "Vibration", "Vibration", "Vibración", "Вібрація"),
    t("Повторяющийся вибросигнал", "Repeating vibration", "Wiederholte Vibration", "Vibration répétée", "Vibración repetida", "Повторюваний вібросигнал"),
    t("Вибрация для остальных событий", "Vibration for later events", "Vibration für spätere Termine", "Vibration pour les événements suivants", "Vibración para eventos posteriores", "Вібрація для наступних подій"),
    t("Только вибрация, без звука", "Vibration only, no sound", "Nur Vibration, kein Ton", "Vibration uniquement, sans son", "Solo vibración, sin sonido", "Лише вібрація, без звуку"),
    t("Упрощённое отключение после времени", "Simplified dismissal after a set time", "Vereinfachtes Ausschalten nach einer Uhrzeit", "Arrêt simplifié après une heure définie", "Desactivación simplificada después de una hora", "Спрощене вимкнення після заданого часу"),
    t("После %s без кнопки «Позже»", "After %s without the Snooze button", "Nach %s ohne Schlummern-Taste", "Après %s sans bouton Reporter", "Después de %s sin el botón Posponer", "Після %s без кнопки «Пізніше»"),
    t("Всегда показывать «Я встал» и «Позже»", "Always show I’m up and Snooze", "Immer Ich bin wach und Schlummern zeigen", "Toujours afficher Je suis debout et Reporter", "Mostrar siempre Ya estoy despierto y Posponer", "Завжди показувати «Я встав» і «Пізніше»"),
    t("Включать упрощённый экран после", "Enable the simplified screen after", "Vereinfachten Bildschirm aktivieren nach", "Activer l’écran simplifié après", "Activar la pantalla simplificada después de", "Вмикати спрощений екран після"),
    t("Как выключать", "Dismiss method", "Ausschaltmethode", "Méthode d’arrêt", "Método de desactivación", "Спосіб вимкнення"),
    t("Кнопка «Готово»", "Done button", "Fertig-Taste", "Bouton Terminé", "Botón Listo", "Кнопка «Готово»"),
    t("Касание экрана", "Tap anywhere", "Bildschirm berühren", "Toucher l’écran", "Tocar la pantalla", "Торкання екрана"),
    t("Сигналы", "Signals", "Signale", "Signaux", "Señales", "Сигнали"),
    t("Яркость, фонарик и сила вибрации", "Brightness, flashlight and vibration strength", "Helligkeit, Taschenlampe und Vibrationsstärke", "Luminosité, lampe torche et intensité de vibration", "Brillo, linterna e intensidad de vibración", "Яскравість, ліхтарик і сила вібрації"),
    t("Первое событие дня", "First event of the day", "Erster Termin des Tages", "Premier événement du jour", "Primer evento del día", "Перша подія дня"),
    t("Остальные события", "Later events", "Weitere Termine", "Événements suivants", "Eventos posteriores", "Наступні події"),
    t("Высокая яркость экрана", "High screen brightness", "Hohe Bildschirmhelligkeit", "Luminosité élevée de l’écran", "Brillo alto de pantalla", "Висока яскравість екрана"),
    t("На время сигнала экран будет максимально ярким", "The screen will be at maximum brightness during the alert", "Während des Signals ist der Bildschirm maximal hell", "L’écran sera à sa luminosité maximale pendant l’alerte", "La pantalla tendrá el brillo máximo durante la alerta", "Під час сигналу екран матиме максимальну яскравість"),
    t("Фонарик", "Flashlight", "Taschenlampe", "Lampe torche", "Linterna", "Ліхтарик"),
    t("Использовать заднюю вспышку телефона", "Use the phone’s rear flash", "Rückseitigen Blitz des Telefons verwenden", "Utiliser le flash arrière du téléphone", "Usar el flash trasero del teléfono", "Використовувати задній спалах телефона"),
    t("Разрешить доступ к фонарику", "Allow flashlight access", "Zugriff auf die Taschenlampe erlauben", "Autoriser l’accès à la lampe torche", "Permitir acceso a la linterna", "Дозволити доступ до ліхтарика"),
    t("Режим фонарика", "Flashlight mode", "Taschenlampenmodus", "Mode de la lampe torche", "Modo de linterna", "Режим ліхтарика"),
    t("Светить постоянно", "Stay on", "Dauerlicht", "Rester allumée", "Luz continua", "Світити постійно"),
    t("Моргать", "Blink", "Blinken", "Clignoter", "Parpadear", "Блимати"),
    t("Скорость мигания", "Blink speed", "Blinkgeschwindigkeit", "Vitesse de clignotement", "Velocidad de parpadeo", "Швидкість блимання"),
    t("%d мс", "%d ms", "%d ms", "%d ms", "%d ms", "%d мс"),
    t("Количество миганий", "Number of flashes", "Anzahl der Blinksignale", "Nombre de clignotements", "Número de destellos", "Кількість блимань"),
    t("Настраиваемая сила вибросигнала", "Adjustable vibration strength", "Einstellbare Vibrationsstärke", "Intensité de vibration réglable", "Intensidad de vibración ajustable", "Налаштовувана сила вібросигналу"),
    t("Сила вибрации", "Vibration strength", "Vibrationsstärke", "Intensité de vibration", "Intensidad de vibración", "Сила вібрації"),
    t("яркий экран", "bright screen", "heller Bildschirm", "écran lumineux", "pantalla brillante", "яскравий екран"),
    t("мигающий фонарик", "blinking flashlight", "blinkende Taschenlampe", "lampe torche clignotante", "linterna intermitente", "блимання ліхтарика"),
    t("фонарик", "flashlight", "Taschenlampe", "lampe torche", "linterna", "ліхтарик"),
    t("вибрация %d%%", "vibration %d%%", "Vibration %d%%", "vibration %d%%", "vibración %d%%", "вібрація %d%%"),
    t("Без дополнительных эффектов", "No additional effects", "Keine zusätzlichen Effekte", "Aucun effet supplémentaire", "Sin efectos adicionales", "Без додаткових ефектів"),
    t("Коснитесь экрана, чтобы выключить", "Tap the screen to dismiss", "Zum Ausschalten Bildschirm berühren", "Touchez l’écran pour arrêter", "Toca la pantalla para desactivar", "Торкніться екрана, щоб вимкнути"),
    t("Отложить сигнал", "Snooze", "Schlummern", "Reporter l’alarme", "Posponer alarma", "Відкласти сигнал"),
    t("Автоматически выключить звук", "Auto-silence", "Automatisch stummschalten", "Arrêt automatique du son", "Silenciar automáticamente", "Автоматично вимкнути звук"),
    t("Дни недели", "Days of week", "Wochentage", "Jours de la semaine", "Días de la semana", "Дні тижня"),
    t("В какие дни создавать будильник", "Days when alarms are created", "Tage für Wecker", "Jours de création des alarmes", "Días para crear alarmas", "У які дні створювати будильник"),
    t("Ни один день не выбран — будильники не создаются", "No day selected — no alarms will be created", "Kein Tag gewählt – es werden keine Wecker erstellt", "Aucun jour choisi — aucune alarme ne sera créée", "No hay días seleccionados: no se crearán alarmas", "Не вибрано жодного дня — будильники не створюються"),
    t("Календари", "Calendars", "Kalender", "Calendriers", "Calendarios", "Календарі"),
    t("Источники событий на этом телефоне", "Event sources on this phone", "Termin-Quellen auf diesem Telefon", "Sources d’événements sur ce téléphone", "Fuentes de eventos de este teléfono", "Джерела подій на цьому телефоні"),
    t("Приложение может включить выбранные календари и запросить их синхронизацию у Android.", "The app can enable selected calendars and ask Android to sync them.", "Die App kann ausgewählte Kalender aktivieren und Android um Synchronisierung bitten.", "L’application peut activer les calendriers sélectionnés et demander leur synchronisation à Android.", "La aplicación puede activar los calendarios seleccionados y pedir a Android que los sincronice.", "Застосунок може ввімкнути вибрані календарі й попросити Android синхронізувати їх."),
    t("Исправить и синхронизировать", "Repair and sync", "Reparieren und synchronisieren", "Réparer et synchroniser", "Reparar y sincronizar", "Виправити й синхронізувати"),
    t("Разрешить управление календарями", "Allow calendar management", "Kalenderverwaltung erlauben", "Autoriser la gestion des calendriers", "Permitir gestionar calendarios", "Дозволити керування календарями"),
    t("Разрешить доступ к календарю", "Allow calendar access", "Kalenderzugriff erlauben", "Autoriser l’accès au calendrier", "Permitir acceso al calendario", "Дозволити доступ до календаря"),
    t("На устройстве не найдено календарей", "No calendars found on this device", "Keine Kalender auf dem Gerät gefunden", "Aucun calendrier trouvé sur l’appareil", "No se encontraron calendarios en el dispositivo", "На пристрої не знайдено календарів"),
    t("Найдено общих календарей: %d", "Shared calendars found: %d", "Freigegebene Kalender gefunden: %d", "Calendriers partagés trouvés : %d", "Calendarios compartidos encontrados: %d", "Знайдено спільних календарів: %d"),
    t("У календарей без синхронизации Android может не хранить события. Включите их синхронизацию в Google Calendar; уже загруженные записи приложение проверит напрямую.", "Android may not store events from calendars with sync disabled. Enable sync in Google Calendar; the app checks already downloaded entries directly.", "Android speichert Termine aus Kalendern ohne Synchronisierung eventuell nicht. Aktivieren Sie die Synchronisierung in Google Kalender; bereits geladene Einträge werden direkt geprüft.", "Android peut ne pas stocker les événements des calendriers non synchronisés. Activez la synchronisation dans Google Agenda ; les entrées déjà téléchargées sont vérifiées directement.", "Android puede no guardar eventos de calendarios sin sincronización. Actívala en Google Calendar; la aplicación revisa directamente los eventos ya descargados.", "Android може не зберігати події календарів без синхронізації. Увімкніть її в Google Calendar; уже завантажені записи застосунок перевірить безпосередньо."),
    t("Скрытые календари тоже проверяются напрямую, но повторяющиеся события надёжнее читать после включения показа календаря.", "Hidden calendars are also checked directly, but recurring events are more reliable when the calendar is visible.", "Ausgeblendete Kalender werden ebenfalls direkt geprüft; Serientermine sind jedoch zuverlässiger, wenn der Kalender sichtbar ist.", "Les calendriers masqués sont aussi vérifiés directement, mais les événements récurrents sont plus fiables lorsque le calendrier est visible.", "Los calendarios ocultos también se revisan directamente, pero los eventos recurrentes son más fiables si el calendario está visible.", "Приховані календарі також перевіряються безпосередньо, але повторювані події надійніше читати, коли календар видимий."),
    t("Общий", "Shared", "Freigegeben", "Partagé", "Compartido", "Спільний"),
    t("синхронизация выключена", "sync is off", "Synchronisierung aus", "synchronisation désactivée", "sincronización desactivada", "синхронізацію вимкнено"),
    t("календарь скрыт", "calendar is hidden", "Kalender ausgeblendet", "calendrier masqué", "calendario oculto", "календар приховано"),
    t("владелец %s", "owner %s", "Eigentümer %s", "propriétaire %s", "propietario %s", "власник %s"),
    t("Все календари уже выбраны", "All calendars are selected", "Alle Kalender sind ausgewählt", "Tous les calendriers sont sélectionnés", "Todos los calendarios están seleccionados", "Усі календарі вже вибрані"),
    t("Выбрать все календари", "Select all calendars", "Alle Kalender auswählen", "Sélectionner tous les calendriers", "Seleccionar todos los calendarios", "Вибрати всі календарі"),
    t("Планирование", "Planning", "Planung", "Planification", "Planificación", "Планування"),
    t("Ежедневно в %s", "Daily at %s", "Täglich um %s", "Chaque jour à %s", "Cada día a las %s", "Щодня о %s"),
    t("Время проверки календарей", "Calendar check time", "Zeit der Kalenderprüfung", "Heure de vérification", "Hora de revisión", "Час перевірки календарів"),
    t("Точное планирование включено", "Exact scheduling enabled", "Genaue Planung aktiviert", "Planification exacte activée", "Planificación exacta activada", "Точне планування ввімкнено"),
    t("Разрешить точное время", "Allow exact timing", "Genaue Zeit erlauben", "Autoriser l’heure exacte", "Permitir hora exacta", "Дозволити точний час"),
    t("Ещё не проверялось", "Not checked yet", "Noch nicht geprüft", "Pas encore vérifié", "Aún no se ha revisado", "Ще не перевірялося"),
    t("Последняя проверка %s", "Last checked %s", "Zuletzt geprüft %s", "Dernière vérification %s", "Última revisión %s", "Остання перевірка %s"),
    t("Ошибки и журнал", "Errors and log", "Fehler und Protokoll", "Erreurs et journal", "Errores y registro", "Помилки та журнал"),
    t("Нажмите, чтобы скрыть", "Tap to hide", "Zum Ausblenden tippen", "Touchez pour masquer", "Toca para ocultar", "Натисніть, щоб приховати"),
    t("Скрыто · нажмите, чтобы раскрыть", "Hidden · tap to expand", "Ausgeblendet · zum Öffnen tippen", "Masqué · touchez pour ouvrir", "Oculto · toca para abrir", "Приховано · натисніть, щоб розкрити"),
    t("Есть ошибка · нажмите, чтобы раскрыть", "Error found · tap to expand", "Fehler gefunden · zum Öffnen tippen", "Erreur détectée · touchez pour ouvrir", "Hay un error · toca para abrir", "Є помилка · натисніть, щоб розкрити"),
    t("Есть ошибки чтения · нажмите, чтобы раскрыть", "Read warnings found · tap to expand", "Lesewarnungen · zum Öffnen tippen", "Avertissements de lecture · touchez pour ouvrir", "Hay avisos de lectura · toca para abrir", "Є попередження читання · натисніть, щоб розкрити"),
    t("Ошибка приложения: %s", "App error: %s", "App-Fehler: %s", "Erreur de l’application : %s", "Error de la aplicación: %s", "Помилка застосунку: %s"),
    t("Календари Android", "Android calendars", "Android-Kalender", "Calendriers Android", "Calendarios de Android", "Календарі Android"),
    t("Android передал события", "Events returned by Android", "Von Android gelieferte Termine", "Événements transmis par Android", "Eventos devueltos por Android", "Події, передані Android"),
    t("Найдено: %d · подходящих: %d · Instances: %d · Events: %d · без синхронизации: %d · скрыто: %d", "Found: %d · matching: %d · Instances: %d · Events: %d · sync off: %d · hidden: %d", "Gefunden: %d · passend: %d · Instances: %d · Events: %d · Sync aus: %d · verborgen: %d", "Trouvés : %d · correspondants : %d · Instances : %d · Events : %d · sans synchro : %d · masqués : %d", "Encontrados: %d · compatibles: %d · Instances: %d · Events: %d · sin sincronizar: %d · ocultos: %d", "Знайдено: %d · відповідних: %d · Instances: %d · Events: %d · без синхронізації: %d · приховано: %d"),
    t("Если у календаря «событий: 0», Android не сохранил его записи на телефоне. Включите синхронизацию и показ этого календаря в Google Calendar, затем нажмите «Проверить сейчас».", "If a calendar shows “events: 0”, Android has not stored its entries on the phone. Enable sync and visibility in Google Calendar, then tap “Check now”.", "Wenn ein Kalender „Termine: 0“ zeigt, hat Android seine Einträge nicht gespeichert. Synchronisierung und Sichtbarkeit in Google Kalender aktivieren und dann „Jetzt prüfen“ tippen.", "Si un calendrier affiche « événements : 0 », Android n’a pas stocké ses entrées. Activez sa synchronisation et son affichage dans Google Agenda, puis touchez « Vérifier maintenant ».", "Si un calendario muestra « eventos: 0 », Android no ha guardado sus entradas. Activa la sincronización y visibilidad en Google Calendar y pulsa « Revisar ahora ».", "Якщо календар показує «подій: 0», Android не зберіг його записи на телефоні. Увімкніть синхронізацію й показ у Google Calendar, потім натисніть «Перевірити зараз»."),
    t("Если у календаря «событий: 0», Android не сохранил его записи. Нажмите кнопку ниже — приложение включит календарь и запросит синхронизацию.", "If a calendar shows “events: 0”, Android has not stored its entries. Tap below to enable the calendar and request a sync.", "Wenn ein Kalender „Termine: 0“ zeigt, hat Android seine Einträge nicht gespeichert. Unten tippen, um den Kalender zu aktivieren und zu synchronisieren.", "Si un calendrier affiche « événements : 0 », Android n’a pas stocké ses entrées. Touchez ci-dessous pour l’activer et demander la synchronisation.", "Si un calendario muestra « eventos: 0 », Android no ha guardado sus entradas. Pulsa abajo para activarlo y solicitar la sincronización.", "Якщо календар показує «подій: 0», Android не зберіг його записи. Натисніть нижче, щоб увімкнути календар і запустити синхронізацію."),
    t("Копий: %d · выбрано: %d · активно: %d · событий: %d", "Copies: %d · selected: %d · active: %d · events: %d", "Kopien: %d · gewählt: %d · aktiv: %d · Termine: %d", "Copies : %d · sélectionnées : %d · actives : %d · événements : %d", "Copias: %d · seleccionadas: %d · activas: %d · eventos: %d", "Копій: %d · вибрано: %d · активно: %d · подій: %d"),
    t("Копий: %d · выбрано: %d · синхр.: %d · событий: %d", "Copies: %d · selected: %d · synced: %d · events: %d", "Kopien: %d · gewählt: %d · synchronisiert: %d · Termine: %d", "Copies : %d · sélectionnées : %d · synchronisées : %d · événements : %d", "Copias: %d · seleccionadas: %d · sincronizadas: %d · eventos: %d", "Копій: %d · вибрано: %d · синхр.: %d · подій: %d"),
    t("Ни одной записи о событиях на ближайшие %d дней.", "No event records for the next %d days.", "Keine Termineinträge für die nächsten %d Tage.", "Aucune entrée d’événement pour les %d prochains jours.", "No hay registros de eventos para los próximos %d días.", "Жодного запису про події на найближчі %d днів."),
    t("Сначала нажмите «Проверить сейчас»", "Tap “Check now” first", "Zuerst „Jetzt prüfen“ tippen", "Touchez d’abord « Vérifier maintenant »", "Primero pulsa « Revisar ahora »", "Спочатку натисніть «Перевірити зараз»"),
    t("Проверить сейчас", "Check now", "Jetzt prüfen", "Vérifier maintenant", "Revisar ahora", "Перевірити зараз"),
    t("Разрешите управление календарями для восстановления синхронизации", "Allow calendar management to restore sync", "Kalenderverwaltung erlauben, um die Synchronisierung wiederherzustellen", "Autorisez la gestion des calendriers pour rétablir la synchronisation", "Permite gestionar calendarios para restaurar la sincronización", "Дозвольте керування календарями, щоб відновити синхронізацію"),
    t("Android не разрешил включить календарей: %d", "Android did not allow enabling %d calendars", "Android erlaubte das Aktivieren von %d Kalendern nicht", "Android n’a pas autorisé l’activation de %d calendriers", "Android no permitió activar %d calendarios", "Android не дозволив увімкнути календарів: %d"),
    t("Синхронизация восстановлена для календарей: %d. Найдено событий: %d", "Sync restored for %d calendars. Events found: %d", "Synchronisierung für %d Kalender wiederhergestellt. Termine gefunden: %d", "Synchronisation rétablie pour %d calendriers. Événements trouvés : %d", "Sincronización restaurada para %d calendarios. Eventos encontrados: %d", "Синхронізацію відновлено для календарів: %d. Знайдено подій: %d"),
    t("Обновления", "Updates", "Updates", "Mises à jour", "Actualizaciones", "Оновлення"),
    t("Через GitHub Releases", "Through GitHub Releases", "Über GitHub Releases", "Via GitHub Releases", "Mediante GitHub Releases", "Через GitHub Releases"),
    t("Проверять автоматически", "Check automatically", "Automatisch prüfen", "Vérifier automatiquement", "Comprobar automáticamente", "Перевіряти автоматично"),
    t("APK загрузится сам; установку подтверждает Android", "The APK downloads automatically; Android asks before installation", "Die APK wird automatisch geladen; Android bestätigt die Installation", "L’APK se télécharge automatiquement ; Android confirme l’installation", "El APK se descarga solo; Android confirma la instalación", "APK завантажиться автоматично; установлення підтверджує Android"),
    t("Проверить обновления", "Check for updates", "Nach Updates suchen", "Rechercher les mises à jour", "Buscar actualizaciones", "Перевірити оновлення"),
    t("Репозиторий не настроен", "Repository not configured", "Repository nicht eingerichtet", "Dépôt non configuré", "Repositorio no configurado", "Репозиторій не налаштовано"),
    t("Экономно для батареи", "Battery efficient", "Akkuschonend", "Économe en batterie", "Ahorra batería", "Економно для батареї"),
    t("Одна плановая проверка в сутки и только нужные системные сигналы — без постоянного сервиса.", "One scheduled check per day and only required system alarms — no permanent service.", "Eine geplante Prüfung pro Tag und nur nötige Systemwecker – kein dauerhafter Dienst.", "Une vérification par jour et uniquement les alarmes système nécessaires — aucun service permanent.", "Una revisión programada al día y solo las alarmas necesarias, sin servicio permanente.", "Одна планова перевірка на добу й лише потрібні системні сигнали — без постійної служби."),
    t("Опережение будильника", "Alarm lead time", "Vorlaufzeit des Weckers", "Avance de l’alarme", "Antelación de la alarma", "Випередження будильника"),
    t("Можно выбрать от момента начала до 14 суток заранее.", "Choose from the start time up to 14 days before.", "Von der Startzeit bis zu 14 Tage vorher wählbar.", "Choisissez entre l’heure de début et 14 jours avant.", "Elige desde la hora de inicio hasta 14 días antes.", "Можна вибрати від моменту початку до 14 діб заздалегідь."),
    t("Дни", "Days", "Tage", "Jours", "Días", "Дні"),
    t("Часы", "Hours", "Stunden", "Heures", "Horas", "Години"),
    t("Мин", "Min", "Min", "Min", "Min", "Хв"),
    t("Сохранить", "Save", "Speichern", "Enregistrer", "Guardar", "Зберегти"),
    t("Отмена", "Cancel", "Abbrechen", "Annuler", "Cancelar", "Скасувати"),
    t("В момент начала", "At start time", "Zum Startzeitpunkt", "À l’heure de début", "A la hora de inicio", "У момент початку"),
    t("%d дн", "%d d", "%d T", "%d j", "%d d", "%d дн"),
    t("%d ч", "%d h", "%d Std", "%d h", "%d h", "%d год"),
    t("%d мин", "%d min", "%d Min", "%d min", "%d min", "%d хв"),
    t("Итого: %s", "Total: %s", "Gesamt: %s", "Total : %s", "Total: %s", "Разом: %s"),
    t("Версия %s", "Version %s", "Version %s", "Version %s", "Versión %s", "Версія %s"),
    t("Сегодня", "Today", "Heute", "Aujourd’hui", "Hoy", "Сьогодні"),
    t("Завтра", "Tomorrow", "Morgen", "Demain", "Mañana", "Завтра"),
    t("скоро", "soon", "bald", "bientôt", "pronto", "скоро"),
    t("через %d дн.", "in %d d", "in %d T", "dans %d j", "en %d d", "через %d дн."),
    t("через %d ч", "in %d h", "in %d Std", "dans %d h", "en %d h", "через %d год"),
    t("Пора собираться", "Time to get ready", "Zeit, sich fertig zu machen", "Il est temps de se préparer", "Hora de prepararse", "Час збиратися"),
    t("ПОРА СОБИРАТЬСЯ", "TIME TO GET READY", "ZEIT, SICH FERTIG ZU MACHEN", "IL EST TEMPS DE SE PRÉPARER", "HORA DE PREPARARSE", "ЧАС ЗБИРАТИСЯ"),
    t("Весь день", "All day", "Ganztägig", "Toute la journée", "Todo el día", "Увесь день"),
    t("Я встал", "I’m up", "Ich bin wach", "Je suis debout", "Ya estoy despierto", "Я встав"),
    t("Отложить на %d мин", "Snooze for %d min", "%d Min schlummern", "Reporter de %d min", "Posponer %d min", "Відкласти на %d хв"),
    t("Подготавливаем обновление…", "Preparing update…", "Update wird vorbereitet…", "Préparation de la mise à jour…", "Preparando actualización…", "Готуємо оновлення…"),
    t("Старая версия загружена; Android не установит её поверх новой", "An older version was downloaded; Android will not install it over a newer one", "Eine ältere Version wurde geladen; Android installiert sie nicht über einer neueren", "Une ancienne version a été téléchargée ; Android ne l’installera pas sur une version plus récente", "Se descargó una versión anterior; Android no la instalará sobre una más nueva", "Стару версію завантажено; Android не встановить її поверх новішої"),
    t("Доступно обновление", "Update available", "Update verfügbar", "Mise à jour disponible", "Actualización disponible", "Доступне оновлення"),
    t("Переход на старую версию", "Switch to an older version", "Zu einer älteren Version wechseln", "Passer à une ancienne version", "Cambiar a una versión anterior", "Перехід на стару версію"),
    t("Версия %s уже загружена и готова к установке", "Version %s is downloaded and ready to install", "Version %s wurde heruntergeladen und kann installiert werden", "La version %s est téléchargée et prête à être installée", "La versión %s está descargada y lista para instalar", "Версію %s завантажено й підготовлено до встановлення"),
    t("Установить сейчас? Android покажет системное подтверждение.", "Install now? Android will show a system confirmation.", "Jetzt installieren? Android zeigt eine Systembestätigung.", "Installer maintenant ? Android affichera une confirmation système.", "¿Instalar ahora? Android mostrará una confirmación del sistema.", "Встановити зараз? Android покаже системне підтвердження."),
    t("Это старая версия. Android не установит её поверх более новой.", "This is an older version. Android will not install it over a newer one.", "Dies ist eine ältere Version. Android installiert sie nicht über einer neueren.", "Il s’agit d’une ancienne version. Android ne l’installera pas sur une version plus récente.", "Esta es una versión anterior. Android no la instalará sobre una más nueva.", "Це стара версія. Android не встановить її поверх новішої."),
    t("Android запрещает ставить старую версию поверх новой. Сначала сохраним APK в папку «Загрузки».", "Android blocks installing an older version over a newer one. First, we’ll save the APK to Downloads.", "Android verhindert die Installation einer älteren über einer neueren Version. Zuerst speichern wir die APK unter Downloads.", "Android bloque l’installation d’une ancienne version sur une plus récente. Nous allons d’abord enregistrer l’APK dans Téléchargements.", "Android impide instalar una versión anterior sobre una nueva. Primero guardaremos el APK en Descargas.", "Android забороняє встановлювати стару версію поверх нової. Спочатку збережемо APK у «Завантаження»."),
    t("Сохраняем проверенный APK в папку «Загрузки»…", "Saving the verified APK to Downloads…", "Die geprüfte APK wird unter Downloads gespeichert…", "Enregistrement de l’APK vérifié dans Téléchargements…", "Guardando el APK verificado en Descargas…", "Зберігаємо перевірений APK у «Завантаження»…"),
    t("APK сохранён: %s\n\n1. Удалите текущую версию кнопкой ниже.\n2. Откройте «Загрузки» и установите сохранённый APK.", "APK saved: %s\n\n1. Remove the current version using the button below.\n2. Open Downloads and install the saved APK.", "APK gespeichert: %s\n\n1. Entfernen Sie die aktuelle Version über die Schaltfläche unten.\n2. Öffnen Sie Downloads und installieren Sie die gespeicherte APK.", "APK enregistré : %s\n\n1. Supprimez la version actuelle avec le bouton ci-dessous.\n2. Ouvrez Téléchargements et installez l’APK enregistré.", "APK guardado: %s\n\n1. Elimina la versión actual con el botón de abajo.\n2. Abre Descargas e instala el APK guardado.", "APK збережено: %s\n\n1. Видаліть поточну версію кнопкою нижче.\n2. Відкрийте «Завантаження» та встановіть збережений APK."),
    t("Не удалось сохранить APK: %s", "Could not save the APK: %s", "APK konnte nicht gespeichert werden: %s", "Impossible d’enregistrer l’APK : %s", "No se pudo guardar el APK: %s", "Не вдалося зберегти APK: %s"),
    t("Установить", "Install", "Installieren", "Installer", "Instalar", "Встановити"),
    t("Подготовить переход", "Prepare switch", "Wechsel vorbereiten", "Préparer le changement", "Preparar cambio", "Підготувати перехід"),
    t("Сохраняем APK…", "Saving APK…", "APK wird gespeichert…", "Enregistrement de l’APK…", "Guardando APK…", "Зберігаємо APK…"),
    t("Удалить текущую версию", "Remove current version", "Aktuelle Version entfernen", "Supprimer la version actuelle", "Eliminar versión actual", "Видалити поточну версію"),
    t("Открыть «Загрузки»", "Open Downloads", "Downloads öffnen", "Ouvrir Téléchargements", "Abrir Descargas", "Відкрити «Завантаження»"),
    t("При удалении выберите «Сохранить данные приложения», если Android предложит. Разрешения иногда нужно выдать заново.", "When removing, choose “Keep app data” if Android offers it. You may need to grant permissions again.", "Wählen Sie beim Entfernen „App-Daten behalten“, falls Android dies anbietet. Berechtigungen müssen eventuell erneut erteilt werden.", "Lors de la suppression, choisissez « Conserver les données de l’application » si Android le propose. Il faudra parfois accorder à nouveau les autorisations.", "Al eliminar, elige «Conservar datos de la aplicación» si Android lo ofrece. Puede que tengas que volver a conceder permisos.", "Під час видалення виберіть «Зберегти дані застосунку», якщо Android запропонує. Дозволи іноді потрібно надати повторно."),
    t("неизвестная ошибка", "unknown error", "unbekannter Fehler", "erreur inconnue", "error desconocido", "невідома помилка"),
    t("Позже", "Later", "Später", "Plus tard", "Más tarde", "Пізніше"),
    t("Свернуть", "Collapse", "Einklappen", "Réduire", "Contraer", "Згорнути"),
    t("Развернуть", "Expand", "Ausklappen", "Développer", "Expandir", "Розгорнути"),
    t("Будильник готов", "Alarm ready", "Wecker bereit", "Alarme prête", "Alarma lista", "Будильник готовий"),
    t("На ближайшие дни будильников нет", "No alarms for the coming days", "Keine Wecker für die nächsten Tage", "Aucune alarme pour les prochains jours", "No hay alarmas para los próximos días", "На найближчі дні будильників немає"),
    t("Сигнал перед событием", "Alarm before an event", "Wecker vor einem Termin", "Alarme avant un événement", "Alarma antes de un evento", "Сигнал перед подією"),
    t("Итог ежедневной проверки календаря", "Daily calendar check summary", "Ergebnis der täglichen Kalenderprüfung", "Résumé de la vérification quotidienne", "Resumen de la revisión diaria", "Підсумок щоденної перевірки календаря"),
    t("Новые версии из GitHub Releases", "New versions from GitHub Releases", "Neue Versionen aus GitHub Releases", "Nouvelles versions de GitHub Releases", "Nuevas versiones de GitHub Releases", "Нові версії з GitHub Releases"),
    t("звук и вибрация", "sound and vibration", "Ton und Vibration", "son et vibration", "sonido y vibración", "звук і вібрація"),
    t("только звук", "sound only", "nur Ton", "son uniquement", "solo sonido", "лише звук"),
    t("только вибрация", "vibration only", "nur Vibration", "vibration uniquement", "solo vibración", "лише вібрація"),
    t("без звука", "silent", "lautlos", "silencieux", "silencioso", "без звуку"),
    t("События не прочитаны: проверьте синхронизацию календарей", "Events could not be read: check calendar sync", "Termine konnten nicht gelesen werden: Kalendersynchronisierung prüfen", "Événements non lus : vérifiez la synchronisation", "No se pudieron leer los eventos: revisa la sincronización", "Події не прочитано: перевірте синхронізацію календарів"),
    t("Календарь не вернул событий на ближайшие %d дней", "The calendar returned no events for the next %d days", "Der Kalender lieferte für die nächsten %d Tage keine Termine", "Le calendrier n’a renvoyé aucun événement pour les %d prochains jours", "El calendario no devolvió eventos para los próximos %d días", "Календар не повернув подій на найближчі %d днів"),
    t("Календарь проверен — события не прошли выбранные фильтры", "Calendar checked — events did not match the selected filters", "Kalender geprüft – Termine entsprachen nicht den gewählten Filtern", "Calendrier vérifié — les événements ne correspondent pas aux filtres", "Calendario revisado: los eventos no coinciden con los filtros", "Календар перевірено — події не пройшли вибрані фільтри"),
    t("%s %s готово", "%s %s is ready", "%s %s ist bereit", "%s %s est prête", "%s %s está lista", "%s %s готово"),
    t("Нажмите, чтобы подтвердить установку обновления", "Tap to confirm update installation", "Tippen, um die Installation zu bestätigen", "Touchez pour confirmer l’installation", "Toca para confirmar la instalación", "Натисніть, щоб підтвердити встановлення оновлення"),
    t("Установлена последняя версия", "Latest version is installed", "Die neueste Version ist installiert", "La dernière version est installée", "Está instalada la última versión", "Установлено останню версію"),
    t("В последнем релизе нет APK", "The latest release has no APK", "Das neueste Release enthält keine APK", "La dernière version ne contient pas d’APK", "La última versión no contiene APK", "В останньому релізі немає APK"),
    t("Не удалось прочитать календарь", "Could not read the calendar", "Kalender konnte nicht gelesen werden", "Impossible de lire le calendrier", "No se pudo leer el calendario", "Не вдалося прочитати календар"),
    t("Оставьте хотя бы один календарь", "Keep at least one calendar selected", "Mindestens einen Kalender auswählen", "Gardez au moins un calendrier sélectionné", "Selecciona al menos un calendario", "Залиште вибраним хоча б один календар"),
    t("Версия %s загружена", "Version %s downloaded", "Version %s heruntergeladen", "Version %s téléchargée", "Versión %s descargada", "Версію %s завантажено"),
    t("Обновление: %s", "Update: %s", "Update: %s", "Mise à jour : %s", "Actualización: %s", "Оновлення: %s"),
    t("Календарь прочитан с ошибками — откройте скрытый журнал", "Calendar read with errors — open the hidden log", "Kalender mit Fehlern gelesen – verborgenes Protokoll öffnen", "Calendrier lu avec des erreurs — ouvrez le journal masqué", "Calendario leído con errores: abre el registro oculto", "Календар прочитано з помилками — відкрийте прихований журнал"),
    t("Найдено событий: %d; будильников: %d", "Events found: %d; alarms: %d", "Termine gefunden: %d; Wecker: %d", "Événements trouvés : %d ; alarmes : %d", "Eventos encontrados: %d; alarmas: %d", "Знайдено подій: %d; будильників: %d"),
    t("Будильников: %d; разрешите точное время", "Alarms: %d; allow exact timing", "Wecker: %d; genaue Zeit erlauben", "Alarmes : %d ; autorisez l’heure exacte", "Alarmas: %d; permite la hora exacta", "Будильників: %d; дозвольте точний час"),
    t("Событий не найдено. У %d календарей выключена синхронизация", "No events found. Sync is off for %d calendars", "Keine Termine gefunden. Synchronisierung ist bei %d Kalendern aus", "Aucun événement trouvé. La synchronisation est désactivée pour %d calendriers", "No se encontraron eventos. %d calendarios no están sincronizados", "Подій не знайдено. У %d календарів вимкнено синхронізацію"),
    t("В ближайшие %d дней календарь не вернул событий", "The calendar returned no events for the next %d days", "Der Kalender lieferte für die nächsten %d Tage keine Termine", "Le calendrier n’a renvoyé aucun événement pour les %d prochains jours", "El calendario no devolvió eventos para los próximos %d días", "Календар не повернув подій на найближчі %d днів"),
    t("Найдены только события на весь день — для них будильник не ставится", "Only all-day events found — no alarms are set for them", "Nur ganztägige Termine gefunden – dafür werden keine Wecker erstellt", "Seuls des événements sur la journée ont été trouvés — aucune alarme n’est créée", "Solo se encontraron eventos de todo el día; no se crean alarmas", "Знайдено лише події на весь день — для них будильник не встановлюється"),
    t("События найдены, но их календари отключены в настройках", "Events found, but their calendars are disabled in settings", "Termine gefunden, aber ihre Kalender sind in den Einstellungen deaktiviert", "Événements trouvés, mais leurs calendriers sont désactivés", "Se encontraron eventos, pero sus calendarios están desactivados", "Події знайдено, але їхні календарі вимкнено в налаштуваннях"),
    t("События найдены, но эти дни недели отключены", "Events found, but those weekdays are disabled", "Termine gefunden, aber diese Wochentage sind deaktiviert", "Événements trouvés, mais ces jours sont désactivés", "Se encontraron eventos, pero esos días están desactivados", "Події знайдено, але ці дні тижня вимкнено"),
    t("События найдены, но начинаются позже заданной метки", "Events found, but they start after the cutoff", "Termine gefunden, beginnen aber nach der Zeitgrenze", "Événements trouvés, mais ils commencent après la limite", "Se encontraron eventos, pero empiezan después del límite", "Події знайдено, але вони починаються пізніше заданої межі"),
    t("События найдены, но время будильника для них уже прошло", "Events found, but their alarm time has passed", "Termine gefunden, aber ihre Weckzeit ist bereits vorbei", "Événements trouvés, mais l’heure de leur alarme est passée", "Se encontraron eventos, pero su hora de alarma ya pasó", "Події знайдено, але час будильника для них уже минув"),
    t("Подходящих событий пока нет", "No matching events yet", "Noch keine passenden Termine", "Aucun événement correspondant pour le moment", "Aún no hay eventos compatibles", "Відповідних подій поки немає"),
    t("Нажмите обновить, чтобы проверить события", "Tap refresh to check events", "Zum Prüfen der Termine auf Aktualisieren tippen", "Touchez Actualiser pour vérifier les événements", "Toca actualizar para revisar los eventos", "Натисніть оновити, щоб перевірити події"),
    t("Android не вернул событий. Проверьте календари с выключенной синхронизацией в настройках", "Android returned no events. Check calendars with sync disabled in settings", "Android lieferte keine Termine. Prüfen Sie Kalender ohne Synchronisierung", "Android n’a renvoyé aucun événement. Vérifiez les calendriers non synchronisés", "Android no devolvió eventos. Revisa los calendarios sin sincronización", "Android не повернув подій. Перевірте календарі з вимкненою синхронізацією"),
    t("Android не вернул событий. Проверьте скрытые календари в настройках", "Android returned no events. Check hidden calendars in settings", "Android lieferte keine Termine. Prüfen Sie ausgeblendete Kalender", "Android n’a renvoyé aucun événement. Vérifiez les calendriers masqués", "Android no devolvió eventos. Revisa los calendarios ocultos", "Android не повернув подій. Перевірте приховані календарі"),
    t("Android не вернул событий на ближайшие %d дней", "Android returned no events for the next %d days", "Android lieferte für die nächsten %d Tage keine Termine", "Android n’a renvoyé aucun événement pour les %d prochains jours", "Android no devolvió eventos para los próximos %d días", "Android не повернув подій на найближчі %d днів"),
    t("Найдены только события на весь день", "Only all-day events found", "Nur ganztägige Termine gefunden", "Seuls des événements sur la journée ont été trouvés", "Solo se encontraron eventos de todo el día", "Знайдено лише події на весь день"),
    t("События есть, но их календари отключены в настройках", "Events exist, but their calendars are disabled in settings", "Termine vorhanden, aber ihre Kalender sind deaktiviert", "Des événements existent, mais leurs calendriers sont désactivés", "Hay eventos, pero sus calendarios están desactivados", "Події є, але їхні календарі вимкнено"),
    t("События есть, но нужные дни недели отключены", "Events exist, but the required weekdays are disabled", "Termine vorhanden, aber die benötigten Wochentage sind deaktiviert", "Des événements existent, mais les jours requis sont désactivés", "Hay eventos, pero los días necesarios están desactivados", "Події є, але потрібні дні тижня вимкнено"),
    t("События начинаются позже заданной метки", "Events start after the cutoff", "Termine beginnen nach der Zeitgrenze", "Les événements commencent après la limite", "Los eventos empiezan después del límite", "Події починаються пізніше заданої межі"),
    t("Время этих будильников уже прошло", "These alarm times have already passed", "Diese Weckzeiten sind bereits vorbei", "L’heure de ces alarmes est déjà passée", "La hora de estas alarmas ya pasó", "Час цих будильників уже минув"),
    t("Проверьте фильтры календарей, дней и времени в настройках", "Check calendar, weekday and time filters in settings", "Kalender-, Wochentag- und Zeitfilter prüfen", "Vérifiez les filtres de calendrier, de jour et d’heure", "Revisa los filtros de calendario, días y hora", "Перевірте фільтри календарів, днів і часу"),
    t("Будильник создан", "Alarm created", "Wecker erstellt", "Alarme créée", "Alarma creada", "Будильник створено"),
    t("Пропущено: событие на весь день", "Skipped: all-day event", "Übersprungen: ganztägiger Termin", "Ignoré : événement sur la journée", "Omitido: evento de todo el día", "Пропущено: подія на весь день"),
    t("Пропущено: событие отменено", "Skipped: canceled event", "Übersprungen: abgesagter Termin", "Ignoré : événement annulé", "Omitido: evento cancelado", "Пропущено: подію скасовано"),
    t("Пропущено: приглашение отклонено", "Skipped: invitation declined", "Übersprungen: Einladung abgelehnt", "Ignoré : invitation refusée", "Omitido: invitación rechazada", "Пропущено: запрошення відхилено"),
    t("Пропущено: календарь отключён в настройках", "Skipped: calendar disabled in settings", "Übersprungen: Kalender deaktiviert", "Ignoré : calendrier désactivé", "Omitido: calendario desactivado", "Пропущено: календар вимкнено"),
    t("Пропущено: день недели отключён", "Skipped: weekday disabled", "Übersprungen: Wochentag deaktiviert", "Ignoré : jour désactivé", "Omitido: día desactivado", "Пропущено: день тижня вимкнено"),
    t("Пропущено: позже временной метки", "Skipped: after cutoff", "Übersprungen: nach Zeitgrenze", "Ignoré : après la limite", "Omitido: después del límite", "Пропущено: пізніше часової межі"),
    t("Пропущено: время будильника уже прошло", "Skipped: alarm time passed", "Übersprungen: Weckzeit vorbei", "Ignoré : heure d’alarme passée", "Omitido: hora de alarma pasada", "Пропущено: час будильника минув"),
    t("Пропущено: на этот день уже выбран более ранний будильник", "Skipped: an earlier alarm is already selected for this day", "Übersprungen: früherer Wecker für diesen Tag gewählt", "Ignoré : une alarme plus tôt est déjà choisie", "Omitido: ya hay una alarma anterior para este día", "Пропущено: на цей день уже вибрано раніший будильник"),
    t("Пропустить", "Skip", "Überspringen", "Ignorer", "Omitir", "Пропустити"),
    t("Вернуть", "Restore", "Wiederherstellen", "Restaurer", "Restaurar", "Повернути"),
    t("Закрыть", "Close", "Schließen", "Fermer", "Cerrar", "Закрити"),
    t("Расширенный режим", "Advanced mode", "Erweiterter Modus", "Mode avancé", "Modo avanzado", "Розширений режим"),
    t("Показаны все тонкие настройки", "All detailed settings are shown", "Alle Detaileinstellungen werden angezeigt", "Tous les réglages détaillés sont affichés", "Se muestran todos los ajustes detallados", "Показано всі детальні налаштування"),
    t("Скрывает сложные настройки и оставляет основные", "Hides complex settings and keeps the essentials", "Blendet komplexe Einstellungen aus und zeigt nur das Wesentliche", "Masque les réglages complexes et conserve l’essentiel", "Oculta los ajustes complejos y deja los esenciales", "Приховує складні налаштування й залишає основні"),
    t("Тема приложения", "App theme", "App-Design", "Thème de l’application", "Tema de la aplicación", "Тема застосунку"),
    t("За сколько поставить будильник", "How early to set the alarm", "Wie früh der Wecker klingeln soll", "Combien de temps avant régler l’alarme", "Con cuánta antelación poner la alarma", "За скільки встановити будильник"),
    t("События, звук и вибрация", "Events, sound and vibration", "Termine, Ton und Vibration", "Événements, son et vibration", "Eventos, sonido y vibración", "Події, звук і вібрація"),
    t("Пропустить все сегодня", "Skip all today", "Heute alle überspringen", "Tout ignorer aujourd’hui", "Omitir todo hoy", "Пропустити все сьогодні"),
    t("Вернуть все сегодня", "Restore all today", "Heute alle wiederherstellen", "Tout restaurer aujourd’hui", "Restaurar todo hoy", "Повернути все сьогодні"),
    t("Отменённые события", "Canceled events", "Abgesagte Termine", "Événements annulés", "Eventos cancelados", "Скасовані події"),
    t("Отменено пользователем", "Canceled by user", "Vom Benutzer abgesagt", "Annulé par l’utilisateur", "Cancelado por el usuario", "Скасовано користувачем"),
    t("Событие пропущено", "Event skipped", "Termin übersprungen", "Événement ignoré", "Evento omitido", "Подію пропущено"),
    t("Событие возвращено", "Event restored", "Termin wiederhergestellt", "Événement restauré", "Evento restaurado", "Подію повернено"),
    t("Все события на сегодня пропущены", "All of today’s events were skipped", "Alle heutigen Termine wurden übersprungen", "Tous les événements d’aujourd’hui ont été ignorés", "Se omitieron todos los eventos de hoy", "Усі сьогоднішні події пропущено"),
    t("Все события на сегодня возвращены", "All of today’s events were restored", "Alle heutigen Termine wurden wiederhergestellt", "Tous les événements d’aujourd’hui ont été restaurés", "Se restauraron todos los eventos de hoy", "Усі сьогоднішні події повернено"),
    t("События пропущены пользователем", "Events were skipped by the user", "Termine wurden vom Benutzer übersprungen", "Les événements ont été ignorés par l’utilisateur", "El usuario omitió los eventos", "Події пропущено користувачем"),
    t("Пропущено пользователем", "Skipped by user", "Vom Benutzer übersprungen", "Ignoré par l’utilisateur", "Omitido por el usuario", "Пропущено користувачем"),
    t("Система", "System", "System", "Système", "Sistema", "Система"),
    t("Язык, разрешения и сведения о приложении", "Language, permissions and app information", "Sprache, Berechtigungen und App-Informationen", "Langue, autorisations et informations sur l’application", "Idioma, permisos e información de la aplicación", "Мова, дозволи та відомості про застосунок"),
    t("Язык приложения", "App language", "App-Sprache", "Langue de l’application", "Idioma de la aplicación", "Мова застосунку"),
    t("Настройки языка Android", "Android language settings", "Android-Spracheinstellungen", "Réglages de langue Android", "Ajustes de idioma de Android", "Налаштування мови Android"),
    t("Изменить язык приложения через систему", "Change the app language in Android settings", "App-Sprache in den Android-Einstellungen ändern", "Modifier la langue de l’application dans les réglages Android", "Cambiar el idioma de la aplicación en los ajustes de Android", "Змінити мову застосунку в налаштуваннях Android"),
    t("Системные разрешения", "System permissions", "Systemberechtigungen", "Autorisations système", "Permisos del sistema", "Системні дозволи"),
    t("Доступы Android для календаря, уведомлений и сигналов", "Android access for calendar, notifications and alarms", "Android-Zugriff für Kalender, Benachrichtigungen und Alarme", "Accès Android au calendrier, aux notifications et aux alarmes", "Accesos de Android para calendario, notificaciones y alarmas", "Доступи Android до календаря, сповіщень і сигналів"),
    t("Канал обновлений", "Update channel", "Update-Kanal", "Canal de mise à jour", "Canal de actualizaciones", "Канал оновлень"),
    t("Стабильная версия", "Stable version", "Stabile Version", "Version stable", "Versión estable", "Стабільна версія"),
    t("Бета-версии", "Beta versions", "Beta-Versionen", "Versions bêta", "Versiones beta", "Бета-версії"),
    t("Только проверенные полные версии", "Only tested stable releases", "Nur geprüfte stabile Versionen", "Uniquement les versions stables vérifiées", "Solo versiones estables verificadas", "Лише перевірені стабільні версії"),
    t("Новые функции раньше, но возможны ошибки", "Get new features earlier, but bugs are possible", "Neue Funktionen früher, mögliche Fehler", "Nouvelles fonctions plus tôt, avec des risques d’erreurs", "Nuevas funciones antes, pero puede haber errores", "Нові функції раніше, але можливі помилки"),
    t("Все версии", "All versions", "Alle Versionen", "Toutes les versions", "Todas las versiones", "Усі версії"),
    t("Скачать стабильную или бета-версию из архива", "Download a stable or beta version from the archive", "Stabile oder Beta-Version aus dem Archiv laden", "Télécharger une version stable ou bêta depuis l’archive", "Descargar una versión estable o beta del archivo", "Завантажити стабільну або бета-версію з архіву"),
    t("Архив стабильных версий", "Stable release archive", "Archiv stabiler Versionen", "Archive des versions stables", "Archivo de versiones estables", "Архів стабільних версій"),
    t("Архив бета-версий", "Beta release archive", "Archiv der Beta-Versionen", "Archive des versions bêta", "Archivo de versiones beta", "Архів бета-версій"),
    t("Для перехода на старую версию приложение сохранит APK в «Загрузки» и покажет нужные шаги.", "To switch to an older version, the app will save the APK to Downloads and show the required steps.", "Für den Wechsel zu einer älteren Version speichert die App die APK unter Downloads und zeigt die nötigen Schritte.", "Pour revenir à une ancienne version, l’application enregistrera l’APK dans Téléchargements et affichera les étapes nécessaires.", "Para cambiar a una versión anterior, la aplicación guardará el APK en Descargas y mostrará los pasos necesarios.", "Для переходу на стару версію застосунок збереже APK у «Завантаження» та покаже потрібні кроки."),
    t("В выбранном канале пока нет версий с APK", "There are no APK releases in this channel yet", "In diesem Kanal gibt es noch keine APK-Versionen", "Aucune version APK dans ce canal pour le moment", "Aún no hay versiones APK en este canal", "У вибраному каналі поки немає версій з APK"),
    t("Обновить список", "Refresh list", "Liste aktualisieren", "Actualiser la liste", "Actualizar lista", "Оновити список"),
    t("Версия %s · новее установленной", "Version %s · newer than installed", "Version %s · neuer als installiert", "Version %s · plus récente que la version installée", "Versión %s · más reciente que la instalada", "Версія %s · новіша за встановлену"),
    t("Версия %s · установлена", "Version %s · installed", "Version %s · installiert", "Version %s · installée", "Versión %s · instalada", "Версія %s · встановлена"),
    t("Версия %s · старая", "Version %s · older", "Version %s · älter", "Version %s · ancienne", "Versión %s · anterior", "Версія %s · стара"),
    t("Скачать", "Download", "Laden", "Télécharger", "Descargar", "Завантажити"),
    t("Перейти", "Switch", "Wechseln", "Changer", "Cambiar", "Перейти"),
    t("Скачать снова", "Download again", "Erneut laden", "Télécharger à nouveau", "Descargar de nuevo", "Завантажити знову"),
    t("В GitHub Releases пока нет APK", "There are no APK files in GitHub Releases yet", "In GitHub Releases gibt es noch keine APK-Dateien", "Aucun APK dans GitHub Releases pour le moment", "Aún no hay APK en GitHub Releases", "У GitHub Releases поки немає APK"),
    t("Не удалось загрузить список версий: %s", "Could not load the version list: %s", "Versionsliste konnte nicht geladen werden: %s", "Impossible de charger la liste des versions : %s", "No se pudo cargar la lista de versiones: %s", "Не вдалося завантажити список версій: %s"),
    t("Загрузка версии %s: %s", "Downloading version %s: %s", "Download von Version %s: %s", "Téléchargement de la version %s : %s", "Descarga de la versión %s: %s", "Завантаження версії %s: %s"),
    t("Не удалось загрузить версию %s", "Could not download version %s", "Version %s konnte nicht geladen werden", "Impossible de télécharger la version %s", "No se pudo descargar la versión %s", "Не вдалося завантажити версію %s"),
    t("Версия %s готова к установке", "Version %s is ready to install", "Version %s kann installiert werden", "La version %s est prête à être installée", "La versión %s está lista para instalar", "Версія %s готова до встановлення"),
    t("Установка версии %s: %s", "Installing version %s: %s", "Installation von Version %s: %s", "Installation de la version %s : %s", "Instalación de la versión %s: %s", "Встановлення версії %s: %s"),
    t("Не удалось подготовить установку версии %s", "Could not prepare version %s for installation", "Installation von Version %s konnte nicht vorbereitet werden", "Impossible de préparer l’installation de la version %s", "No se pudo preparar la instalación de la versión %s", "Не вдалося підготувати встановлення версії %s"),
    t("Старая версия %s загружена. Android не установит её поверх новой", "Older version %s was downloaded. Android will not install it over a newer one", "Die ältere Version %s wurde geladen. Android installiert sie nicht über einer neueren", "L’ancienne version %s a été téléchargée. Android ne l’installera pas sur une version plus récente", "Se descargó la versión anterior %s. Android no la instalará sobre una más nueva", "Стару версію %s завантажено. Android не встановить її поверх новішої"),
    t("найдено резервным запросом", "found by fallback query", "durch Ersatzabfrage gefunden", "trouvé par requête de secours", "encontrado mediante consulta alternativa", "знайдено резервним запитом"),
    t("Будильники и тихие напоминания", "Alarms and silent reminders", "Wecker und stille Erinnerungen", "Alarmes et rappels silencieux", "Alarmas y recordatorios silenciosos", "Будильники й тихі нагадування"),
    t("Напоминать об остальных событиях", "Remind me about later events", "An spätere Termine erinnern", "Rappeler les événements suivants", "Recordar los eventos posteriores", "Нагадувати про наступні події"),
    t("Первое событие — будильник, остальные — без звука и вибрации", "The first event is an alarm; the others have no sound or vibration", "Der erste Termin ist ein Wecker, alle weiteren sind lautlos", "Le premier événement est une alarme, les suivants sont silencieux", "El primer evento es una alarma; los demás no tienen sonido ni vibración", "Перша подія — будильник, решта — без звуку та вібрації"),
    t("Первое событие — будильник, остальные — экран без звука", "The first event is an alarm; the others show a screen without sound", "Der erste Termin ist ein Wecker, die weiteren zeigen einen Bildschirm ohne Ton", "Le premier événement est une alarme, les suivants affichent un écran sans son", "El primer evento es una alarma; los demás muestran una pantalla sin sonido", "Перша подія — будильник, решта показують екран без звуку"),
    t("Только первое событие дня с будильником", "Only the first event of the day has an alarm", "Nur der erste Termin des Tages hat einen Wecker", "Seul le premier événement du jour a une alarme", "Solo el primer evento del día tiene alarma", "Лише перша подія дня має будильник"),
    t("Тихое напоминание · без звука и вибрации", "Silent reminder · no sound or vibration", "Stille Erinnerung · ohne Ton und Vibration", "Rappel silencieux · sans son ni vibration", "Recordatorio silencioso · sin sonido ni vibración", "Тихе нагадування · без звуку та вібрації"),
    t("Напоминание · только вибрация", "Reminder · vibration only", "Erinnerung · nur Vibration", "Rappel · vibration uniquement", "Recordatorio · solo vibración", "Нагадування · лише вібрація"),
    t("Будильник · звук по настройкам", "Alarm · sound as configured", "Wecker · Ton wie eingestellt", "Alarme · son selon les réglages", "Alarma · sonido según los ajustes", "Будильник · звук за налаштуваннями"),
    t("Тихие напоминания", "Silent reminders", "Stille Erinnerungen", "Rappels silencieux", "Recordatorios silenciosos", "Тихі нагадування"),
    t("Напоминания с вибрацией", "Vibrating reminders", "Erinnerungen mit Vibration", "Rappels avec vibration", "Recordatorios con vibración", "Нагадування з вібрацією"),
    t("Экран для последующих событий без звука и вибрации", "Full-screen reminders for later events without sound or vibration", "Vollbild-Erinnerungen für spätere Termine ohne Ton und Vibration", "Rappels plein écran pour les événements suivants, sans son ni vibration", "Recordatorios a pantalla completa para eventos posteriores sin sonido ni vibración", "Повноекранні нагадування про наступні події без звуку та вібрації"),
    t("Экран для последующих событий: только вибрация, без звука", "Full-screen reminders for later events: vibration only, no sound", "Vollbild-Erinnerungen für spätere Termine: nur Vibration, kein Ton", "Rappels plein écran pour les événements suivants : vibration uniquement, sans son", "Recordatorios a pantalla completa para eventos posteriores: solo vibración, sin sonido", "Повноекранні нагадування про наступні події: лише вібрація, без звуку"),
    t("Напоминание о событии", "Event reminder", "Terminerinnerung", "Rappel d’événement", "Recordatorio de evento", "Нагадування про подію"),
    t("ТИХОЕ НАПОМИНАНИЕ", "SILENT REMINDER", "STILLE ERINNERUNG", "RAPPEL SILENCIEUX", "RECORDATORIO SILENCIOSO", "ТИХЕ НАГАДУВАННЯ"),
    t("НАПОМИНАНИЕ · ВИБРАЦИЯ", "REMINDER · VIBRATION", "ERINNERUNG · VIBRATION", "RAPPEL · VIBRATION", "RECORDATORIO · VIBRACIÓN", "НАГАДУВАННЯ · ВІБРАЦІЯ"),
    t("Тихое напоминание создано", "Silent reminder created", "Stille Erinnerung erstellt", "Rappel silencieux créé", "Recordatorio silencioso creado", "Тихе нагадування створено"),
).associateBy(Translation::ru)

fun appLocale(): Locale {
    val language = Locale.getDefault().language.lowercase(Locale.ROOT)
    val tag = if (language in setOf(
            "ru", "en", "de", "fr", "es", "uk",
            "it", "pt", "pl", "nl", "tr", "cs", "ro", "el", "ja", "ko",
        )
    ) {
        language
    } else {
        "en"
    }
    return Locale.forLanguageTag(tag)
}

fun tr(source: String, vararg args: Any?): String {
    val translation = translations[source]
    val language = appLocale().language
    val value = v18Translations[language]?.get(source) ?: v17Translations[language]?.get(source) ?: v16Translations[language]?.get(source) ?: when (language) {
        "ru" -> translation?.ru
        "de" -> translation?.de
        "fr" -> translation?.fr
        "es" -> translation?.es
        "uk" -> translation?.uk
        "en" -> translation?.en
        else -> additionalTranslations[language]?.get(source) ?: translation?.en
    } ?: source
    return if (args.isEmpty()) value else String.format(appLocale(), value, *args)
}
